---------------------------------------------

---------------------------------------------
FORBIDDEN_MONSTERS = { 287, 377 }
MAX_PODS = 90
OPEN_BAGS = false
DISPLAY_GATHER_COUNT = true

AUTO_DELETE = { 304, 383 }  

AUTO_DELETE = {  }
MIN_MONSTERS = 3 
MAX_MONSTERS = 8 



function banking()
npc.npc (100, -1)
if isInDialog() then
npc.reply(-1)
		exchange.putExistingItems()
		exchange.getItem(548, 1) -- take recall		
		exchange.getItem(6964, 1) -- take capital potion
		printMessage("Potions Taken")
	leaveDialog()
end
	inventory.useItem(548) 
	waitMapChange() 
	printMessage("I'm on Saved Zapp Je suis sur Saved Zapp")
end

function capital()
	inventory.useItem(6964) -- Bonta 6965
	waitMapChange() 
	printMessage("I'm in Capital City")
end


function move()
MAX_PODS = 90
	return {

	{ map = "13631488", changeMap = "534" }, --going to Bank
	{ map = "-27,36", changeMap = "top" }, --going to Bank
	{ map = "-26,36", changeMap = "left" }, --going to Bank
	{ map = "144931", door = "218" }, --bank door
	{ map = "144931", door = "175" }, --bank door
	{ map = "144931", door = "262" }, --bank door
	{ map = "8913935", custom = banking }, --bank indoor
	{ map = "8914959", custom = banking }, --bank indoor
	{ map = "8912911", custom = banking }, --bank indoor
	{ map="26,-37", changeMap = "right" },
	
	
	
	
	
	{ map="-20,-20", changeMap = "bottom" },
		{ map="-25,30", changeMap = "top" },		
		{ map="-27,33", changeMap = "right" },
		{ map="-26,33", changeMap = "top" },
		{ map="-26,34", changeMap = "top" },
		{ map="-25,29", changeMap = "top" },
		{ map="-25,28", changeMap = "top" },
		{ map="-25,27", changeMap = "top" },
		{ map="-25,26", changeMap = "top" },
		{ map="-25,25", changeMap = "top" },
		{ map="-25,24", changeMap = "top" },
		{ map="-25,23", changeMap = "top" },
		{ map="-25,22", changeMap = "top" },
		{ map="-25,21", changeMap = "top" },
		{ map="-25,20", changeMap = "top" },
		{ map="-25,19", changeMap = "top" },
		{ map="-25,18", changeMap = "top" },
		{ map="-25,17", changeMap = "top" },
		{ map="-25,16", changeMap = "top" },
		{ map="-25,15", changeMap = "top" },
		{ map="-25,14", changeMap = "top" },
		{ map="-25,13", changeMap = "top" },
		{ map="-24,12", changeMap = "left" },
		{ map="-25,12", changeMap = "top" },
		{ map="-25,11", changeMap = "top" },
		{ map="-25,10", changeMap = "top" },
		{ map="-25,9", changeMap = "top" },
		{ map="-25,8", changeMap = "top" },
		{ map="-25,7", changeMap = "top" },
		{ map="-25,6", changeMap = "top" },
		{ map="-25,5", changeMap = "top" },
		{ map="-25,4", changeMap = "top" },
		{ map="-25,3", changeMap = "top" },
		{ map="-25,2", changeMap = "top" },
		{ map="-25,1", changeMap = "top" },
		{ map="-25,0", changeMap = "top" },
		{ map="-25,-1", changeMap = "top" },
		{ map="-25,-2", changeMap = "top" },
		{ map="-25,-3", changeMap = "top" },
		{ map="-25,-4", changeMap = "top" },
		{ map="-25,-5", changeMap = "top" },
		{ map="-25,-6", changeMap = "top" },
		{ map="-25,-7", changeMap = "top" },
		{ map="-25,-8", changeMap = "top" },
		{ map="-25,-9", changeMap = "top" },
		{ map="-25,-10", changeMap = "top" },
		{ map="-25,-11", changeMap = "top" },
		
		{ map="-25,-11", fight = true, changeMap = "top|left" },
		{ map="-26,-11", fight = true, changeMap = "top|left" },
		{ map="-27,-11", fight = true, changeMap = "top|left" },
		{ map="-28,-11", fight = true, changeMap = "top|left" },
		{ map="-29,-11", fight = true, changeMap = "top" },
		{ map="-29,-12", fight = true, changeMap = "top" }, -- rybki
		{ map="-29,-13", fight = true, changeMap = "top" },
		{ map="-29,-14", fight = true, changeMap = "top" },
		{ map="-29,-16", fight = true, changeMap = "top" },
		{ map="-29,-17", fight = true, changeMap = "top" },
		{ map="-29,-18", fight = true, changeMap = "top" },
		{ map="-29,-15", fight = true, changeMap = "top" },
		{ map="-29,-19", fight = true, changeMap = "top|left" },
		{ map="-30,-19", fight = true, changeMap = "top" },
		{ map="-30,-20", fight = true, changeMap = "right|top" },
		{ map="-30,-21", fight = true, changeMap = "right|top" },
		{ map="-30,-22", fight = true, changeMap = "right|top" },
		{ map="-30,-23", fight = true, changeMap = "right|top" },
		{ map="-30,-24", fight = true, changeMap = "right|top" },
		{ map="-30,-25", fight = true, changeMap = "right|top" },
		{ map="-30,-26", fight = true, changeMap = "right|top" },
		{ map="-30,-27", fight = true, changeMap = "right|top" },
		{ map="-30,-28", fight = true, changeMap = "right|top" },
		{ map="-30,-29", fight = true, changeMap = "right|top" },
		{ map="-30,-30", fight = true, changeMap = "right" },
		{ map="-29,-30", fight = true, changeMap = "right" },
		{ map="-29,-20", fight = true, changeMap = "top" },
		{ map="-29,-21", fight = true, changeMap = "top" },
		{ map="-29,-22", fight = true, changeMap = "top" },
		{ map="-29,-24", fight = true, changeMap = "top" },
		{ map="-29,-23", fight = true, changeMap = "top" },
		{ map="-29,-25", fight = true, changeMap = "right|top" },
		{ map="-29,-26", fight = true, changeMap = "top" },
		{ map="-29,-27", fight = true, changeMap = "right|top" },
		{ map="-29,-28", fight = true, changeMap = "top" },
		{ map="-29,-29", fight = true, changeMap = "top" },
		{ map="-28,-31", fight = true, changeMap = "top|right" },
		{ map="-28,-30", fight = true, changeMap = "top|right" },
		{ map="-28,-32", fight = true, changeMap = "top" },
		{ map="-28,-33", fight = true, changeMap = "top" },
		{ map="-28,-34", fight = true, changeMap = "right" },
		{ map="-27,-34", fight = true, changeMap = "right" },
		{ map="-26,-34", fight = true, changeMap = "bottom" },
		{ map="-26,-33", fight = true, changeMap = "bottom|left" },
		{ map="-26,-32", fight = true, changeMap = "left" },
		{ map="-27,-33", fight = true, changeMap = "bottom" },
		{ map="-27,-32", fight = true, changeMap = "bottom" },
		{ map="-27,-31", fight = true, changeMap = "bottom" },
		{ map="-27,-30", fight = true, changeMap = "bottom" },
		{ map="-27,-29", fight = true, changeMap = "bottom|left" },
		{ map="-27,-28", fight = true, changeMap = "left" },
		{ map="-28,-29", fight = true, changeMap = "bottom" },
		{ map="-28,-28", fight = true, changeMap = "bottom" },
		{ map="-28,-27", fight = true, changeMap = "bottom" },
		{ map="-28,-26", fight = true, changeMap = "bottom" },
		{ map="-28,-25", fight = true, changeMap = "bottom" },
		{ map="-28,-24", fight = true, changeMap = "bottom" },
		{ map="-28,-23", fight = true, changeMap = "bottom" },
		{ map="-28,-22", fight = true, changeMap = "bottom" },
		{ map="-28,-21", fight = true, changeMap = "bottom|right" },
		{ map="-28,-20", fight = true, changeMap = "bottom|right" },
		{ map="-28,-19", fight = true, changeMap = "bottom|right" },
		{ map="-28,-18", fight = true, changeMap = "bottom|right" },
		{ map="-28,-16", fight = true, changeMap = "bottom|right" },
		{ map="-28,-17", fight = true, changeMap = "bottom|right" },
		{ map="-28,-15", fight = true, changeMap = "bottom|right" },
		{ map="-28,-14", fight = true, changeMap = "bottom|right" },
		{ map="-28,-13", fight = true, changeMap = "left" },
		{ map="-28,-12", fight = true, changeMap = "left" },
		{ map="-27,-12", fight = true, changeMap = "left" },
		{ map="-27,-13", fight = true, changeMap = "top" },
		{ map="-27,-14", fight = true, changeMap = "top" },
		{ map="-27,-15", fight = true, changeMap = "top|right" },
		{ map="-27,-16", fight = true, changeMap = "right" },
		{ map="-27,-18", fight = true, changeMap = "right|bottom" },
		{ map="-27,-17", fight = true, changeMap = "right|bottom" },
		{ map="-26,-18", fight = true, changeMap = "bottom" },
		{ map="-27,-20", fight = true, changeMap = "bottom" },
		{ map="-27,-21", fight = true, changeMap = "bottom" },
		{ map="-27,-19", fight = true, changeMap = "bottom" },
		{ map="-25,-17", fight = true, changeMap = "bottom" },
		{ map="-26,-17", fight = true, changeMap = "bottom|right" },
		{ map="-26,-16", fight = true, changeMap = "right" },
		{ map="-25,-16", fight = true, changeMap = "right" },
		{ map="-24,-16", fight = true, changeMap = "right" },
		{ map="-23,-16", fight = true, changeMap = "right" },
		{ map="-22,-16", fight = true, changeMap = "right" },
		{ map="-21,-17", fight = true, changeMap = "top" },
		{ map="-21,-16", fight = true, changeMap = "top" },
		{ map="-21,-18", fight = true, changeMap = "top" },
		{ map="-21,-19", fight = true, changeMap = "top" },
		{ map="-20,-18", fight = true, changeMap = "bottom" }, --god
		{ map="-21,-20", fight = true, changeMap = "top|left" },
		{ map="-21,-21", fight = true, changeMap = "top" },
		{ map="-21,-22", fight = true, changeMap = "top|left" },
		{ map="-21,-23", fight = true, changeMap = "top" },
		{ map="-20,-24", fight = true, changeMap = "bottom|right" },
		{ map="-21,-24", fight = true, changeMap = "top" },
		{ map="-21,-25", fight = true, changeMap = "top" },
		{ map="-21,-26", fight = true, changeMap = "top|left" },
		{ map="-22,-20", fight = true, changeMap = "top" },
		{ map="-22,-22", fight = true, changeMap = "top" },
		{ map="-22,-23", fight = true, changeMap = "top" },
		{ map="-22,-21", fight = true, changeMap = "top" },
		{ map="-22,-24", fight = true, changeMap = "top" },
		{ map="-22,-25", fight = true, changeMap = "top" },
		{ map="-22,-26", fight = true, changeMap = "top" },
		{ map="-22,-27", fight = true, changeMap = "right" },
		{ map="-21,-27", fight = true, changeMap = "top" },
		{ map="-21,-28", fight = true, changeMap = "right|top" },
		{ map="-21,-29", fight = true, changeMap = "right" },
		{ map="-20,-29", fight = true, changeMap = "right|top" },
		{ map="-20,-30", fight = true, changeMap = "right|top" },
		{ map="-20,-31", fight = true, changeMap = "right|top" },
		{ map="-20,-32", fight = true, changeMap = "right|top" },
		{ map="-20,-33", fight = true, changeMap = "right|top" },
		{ map="-20,-34", fight = true, changeMap = "right|top" },
		{ map="-20,-35", fight = true, changeMap = "right" },
		{ map="-19,-31", fight = true, changeMap = "right" },
		{ map="-19,-33", fight = true, changeMap = "right|top" },
		{ map="-19,-32", fight = true, changeMap = "right|top" },
		{ map="-19,-34", fight = true, changeMap = "right|top" },
		{ map="-19,-35", fight = true, changeMap = "right" },
		{ map="-18,-35", fight = true, changeMap = "bottom" },
		{ map="-18,-34", fight = true, changeMap = "bottom" },
		{ map="-18,-33", fight = true, changeMap = "bottom" },
		{ map="-18,-32", fight = true, changeMap = "bottom" },
		{ map="-18,-31", fight = true, changeMap = "bottom" },
		{ map="-18,-30", fight = true, changeMap = "bottom" },
		{ map="-18,-29", fight = true, changeMap = "left" },
		{ map="-19,-30", fight = true, changeMap = "bottom" },
		{ map="-19,-29", fight = true, changeMap = "bottom" },
		{ map="-19,-28", fight = true, changeMap = "bottom" },
		{ map="-19,-27", fight = true, changeMap = "bottom" },
		{ map="-19,-26", fight = true, changeMap = "bottom" },
		{ map="-19,-25", fight = true, changeMap = "bottom|left" },
		{ map="-20,-28", fight = true, changeMap = "top" },
		{ map="-20,-27", fight = true, changeMap = "bottom" },
		{ map="-20,-26", fight = true, changeMap = "bottom|right" },
		{ map="-20,-25", fight = true, changeMap = "bottom" },
		{ map="-20,-23", fight = true, changeMap = "bottom|right" },
		{ map="-20,-22", fight = true, changeMap = "bottom|right" },
		{ map="-19,-24", fight = true, changeMap = "bottom" },
		{ map="-19,-23", fight = true, changeMap = "bottom" },
		{ map="-19,-22", fight = true, changeMap = "bottom" },
		{ map="-19,-21", fight = true, changeMap = "bottom" },
		{ map="-20,-21", fight = true, changeMap = "right" },
		{ map="-19,-20", fight = true, changeMap = "bottom" },
		{ map="-19,-19", fight = true, changeMap = "bottom|left" },
		{ map="-19,-18", fight = true, changeMap = "right|bottom" },
		{ map="-19,-17", fight = true, changeMap = "right|bottom" },
		{ map="-19,-16", fight = true, changeMap = "right|bottom" },
		{ map="-18,-18", fight = true, changeMap = "bottom" },
		{ map="-18,-17", fight = true, changeMap = "bottom" },
		{ map="-18,-16", fight = true, changeMap = "bottom" },
		{ map="-18,-15", fight = true, changeMap = "bottom" },
		{ map="-18,-14", fight = true, changeMap = "left" },
		{ map="-19,-14", fight = true, changeMap = "left|bottom" },
		{ map="-19,-13", fight = true, changeMap = "left|bottom" },
		{ map="-20,-14", fight = true, changeMap = "left|bottom" },
		{ map="-20,-13", fight = true, changeMap = "left|bottom" },
		{ map="-19,-15", fight = true, changeMap = "left|bottom" },
		{ map="-20,-16", fight = true, changeMap = "bottom" },
		{ map="-20,-17", fight = true, changeMap = "bottom" },
		{ map="-20,-19", fight = true, changeMap = "bottom" },
		{ map="-20,-15", fight = true, changeMap = "bottom" },
		{ map="-21,-15", fight = true, changeMap = "bottom" },
		{ map="-21,-14", fight = true, changeMap = "bottom" },
		{ map="-19,-12", fight = true, changeMap = "left" },
		{ map="-20,-12", fight = true, changeMap = "left" },
		{ map="-21,-12", fight = true, changeMap = "left" },
		{ map="-22,-12", fight = true, changeMap = "left" },
		{ map="-23,-12", fight = true, changeMap = "left" },
		{ map="-24,-12", fight = true, changeMap = "left" },
		{ map="-25,-12", fight = true, changeMap = "left" },
		{ map="-26,-12", fight = true, changeMap = "left" },
		{ map="-21,-13", fight = true, changeMap = "bottom" },
		{ map="-26,-15", fight = true, changeMap = "top" },

		
		{ map="-26,35", changeMap = "top" },
		{ map="-27,-21", fight = true, changeMap = "left" },
		{ map="-26,32", changeMap = "top" },
		{ map="-26,30", changeMap = "top" },
		{ map="-26,29", changeMap = "right" },
	
		{ map="-30,-12", fight = true, gather = true, changeMap = "left" },
		{ map="-31,-12", fight = true, gather = true, changeMap = "bottom" },
		{ map="-31,-11", fight = true, gather = true, changeMap = "left" },
		{ map="-32,-11", fight = true, gather = true, changeMap = "left" },
		{ map="-33,-11", fight = true, gather = true, changeMap = "left" },
		{ map="-34,-11", fight = true, gather = true, changeMap = "left" },
		{ map="-35,-11", fight = true, gather = true, changeMap = "bottom" },
		{ map="-35,-10", fight = true, gather = true, changeMap = "right" },
		{ map="-34,-10", fight = true, gather = true, changeMap = "right" },
		{ map="-33,-10", fight = true, gather = true, changeMap = "right" },
		{ map="-32,-10", fight = true, gather = true, changeMap = "top" },

	}
end

function bank()
MAX_PODS = 89
	return {
	
			{ map = "13631488", changeMap = "534" }, --going to Bank
	{ map = "-27,36", changeMap = "top" }, --going to Bank
	{ map = "-26,36", changeMap = "left" }, --going to Bank
	{ map = "144931", door = "218" }, --bank door
	{ map = "144931", door = "175" }, --bank door
	{ map = "144931", door = "262" }, --bank door
	{ map = "8913935", custom = banking }, --bank indoor
	{ map = "8914959", custom = banking }, --bank indoor
	{ map = "8912911", custom = banking }, --bank indoor
	{ map="26,-37", changeMap = "right" },
	
	
	
	
		{ map="-26,35", custom = capital, changeMap = "right" },
		{ map="-27,34", custom = capital, changeMap = "right" },
		{ map="-27,33",  custom = capital, changeMap = "right" },
		{ map="-26,33", custom = capital, changeMap = "right" },  
		{ map="-25,29", custom = capital, changeMap = "right" },  
		{ map="-25,28", custom = capital, changeMap = "right" },   
		{ map="-25,27", custom = capital, changeMap = "right" },   
		{ map="-25,26", custom = capital, changeMap = "right" },   
		{ map="-25,25", custom = capital, changeMap = "right" },   
		{ map="-25,24", custom = capital, changeMap = "right" },   
		{ map="-25,23", custom = capital, changeMap = "right" },   
		{ map="-25,22", custom = capital, changeMap = "right" },   
		{ map="-25,21", custom = capital, changeMap = "right" },   
		{ map="-25,20", custom = capital, changeMap = "right" },   
		{ map="-25,19", custom = capital, changeMap = "right" },   
		{ map="-25,18", custom = capital, changeMap = "right" },   
		{ map="-25,17", custom = capital, changeMap = "right" },   
		{ map="-25,16", custom = capital, changeMap = "right" },   
		{ map="-25,15", custom = capital, changeMap = "right" },   
		{ map="-25,14", custom = capital, changeMap = "right" },   
		{ map="-25,13", custom = capital, changeMap = "right" },   
		{ map="-25,12", custom = capital, changeMap = "right" },   
		{ map="-25,11", custom = capital, changeMap = "right" },   
		{ map="-25,10", custom = capital, changeMap = "right" },   
		{ map="-25,9", custom = capital, changeMap = "right" },   
		{ map="-25,8", custom = capital, changeMap = "right" },   
		{ map="-25,7", custom = capital, changeMap = "right" },   
		{ map="-25,6", custom = capital, changeMap = "right" },   
		{ map="-25,5", custom = capital, changeMap = "right" },   
		{ map="-25,4", custom = capital, changeMap = "right" },   
		{ map="-25,3", custom = capital, changeMap = "right" },   
		{ map="-25,2", custom = capital, changeMap = "right" },   
		{ map="-25,1", custom = capital, changeMap = "right" },   
		{ map="-25,0", custom = capital, changeMap = "right" },   
		{ map="-25,-1", custom = capital, changeMap = "right" },   
		{ map="-25,-2", custom = capital, changeMap = "right" },   
		{ map="-25,-3", custom = capital, changeMap = "right" },   
		{ map="-25,-4", custom = capital, changeMap = "right" },   
		{ map="-25,-5", custom = capital, changeMap = "right" },   
		{ map="-25,-6", custom = capital, changeMap = "right" },   
		{ map="-25,-7", custom = capital, changeMap = "right" },   
		{ map="-25,-8", custom = capital, changeMap = "right" },   
		{ map="-25,-9", custom = capital, changeMap = "right" },   
		{ map="-25,-10", custom = capital, changeMap = "right" },   
		{ map="-25,-11", custom = capital, changeMap = "right" },   
		{ map="-25,-12", custom = capital, changeMap = "right" },   
		{ map="-26,-12", custom = capital, changeMap = "right" },   
		{ map="-27,-12", custom = capital, changeMap = "right" },   
		{ map="-28,-12", custom = capital, changeMap = "right" },   
		{ map="-28,-13", custom = capital, changeMap = "right" },   
		{ map="-29,-13", custom = capital, changeMap = "right" },   
		{ map="-29,-14", custom = capital, changeMap = "right" },   
		{ map="-29,-15", custom = capital, changeMap = "right" },   
		{ map="-29,-16", custom = capital, changeMap = "right" },   
		{ map="-29,-17", custom = capital, changeMap = "right" },   
		{ map="-29,-18", custom = capital, changeMap = "right" },   
		{ map="-29,-19", custom = capital, changeMap = "right" },   
		{ map="-28,-19", custom = capital, changeMap = "right" },   
		{ map="-27,-19", custom = capital, changeMap = "right" },   
		{ map="-27,-18", custom = capital, changeMap = "right" },   
		{ map="-28,-18", custom = capital, changeMap = "right" },   
		{ map="-28,-17", custom = capital, changeMap = "right" },   
		{ map="-27,-17", custom = capital, changeMap = "right" },   
		{ map="-27,-16", custom = capital, changeMap = "right" },   
		{ map="-28,-16", custom = capital, changeMap = "right" },   
		{ map="-28,-15", custom = capital, changeMap = "right" },   
		{ map="-27,-15", custom = capital, changeMap = "right" },   
		{ map="-28,-14", custom = capital, changeMap = "right" },   
		{ map="-27,-14", custom = capital, changeMap = "right" },   
		{ map="-27,-13", custom = capital, changeMap = "right" },   
		{ map="-26,-13", custom = capital, changeMap = "right" },   
		{ map="-25,-14", custom = capital, changeMap = "right" },   
		{ map="-25,-13", custom = capital, changeMap = "right" },   
		{ map="-25,-15", custom = capital, changeMap = "right" },   
		{ map="-26,-15", custom = capital, changeMap = "right" },   
		{ map="-26,-14", custom = capital, changeMap = "right" },   
		{ map="-26,-16", custom = capital, changeMap = "right" },   
		{ map="-26,-17", custom = capital, changeMap = "right" },   
		{ map="-25,-16", custom = capital, changeMap = "right" },   
		{ map="-27,-20", custom = capital, changeMap = "right" },   
		{ map="-28,-20", custom = capital, changeMap = "right" },   
		{ map="-28,-21", custom = capital, changeMap = "right" },   
		{ map="-29,-20", custom = capital, changeMap = "right" },   
		{ map="-29,-21", custom = capital, changeMap = "right" },   
		{ map="-29,-22", custom = capital, changeMap = "right" },   
		{ map="-29,-23", custom = capital, changeMap = "right" },   
		{ map="-28,-22", custom = capital, changeMap = "right" },   
		{ map="-28,-23", custom = capital, changeMap = "right" },   
		{ map="-28,-24", custom = capital, changeMap = "right" },   
		{ map="-28,-25", custom = capital, changeMap = "right" },   
		{ map="-28,-26", custom = capital, changeMap = "right" },   
		{ map="-28,-27", custom = capital, changeMap = "right" },   
		{ map="-28,-28", custom = capital, changeMap = "right" },   
		{ map="-29,-24", custom = capital, changeMap = "right" },   
		{ map="-29,-25", custom = capital, changeMap = "right" },   
		{ map="-29,-26", custom = capital, changeMap = "right" },   
		{ map="-29,-27", custom = capital, changeMap = "right" },   
		{ map="-29,-28", custom = capital, changeMap = "right" },   
		{ map="-28,-29", custom = capital, changeMap = "right" },   
		{ map="-28,-30", custom = capital, changeMap = "right" },   
		{ map="-28,-31", custom = capital, changeMap = "right" },   
		{ map="-28,-32", custom = capital, changeMap = "right" },   
		{ map="-28,-33", custom = capital, changeMap = "right" },   
		{ map="-28,-34", custom = capital, changeMap = "right" },   
		{ map="-27,-34", custom = capital, changeMap = "right" },   
		{ map="-28,-35", custom = capital, changeMap = "right" },   
		{ map="-27,-35", custom = capital, changeMap = "right" },   
		{ map="-26,-35", custom = capital, changeMap = "right" },   
		{ map="-26,-36", custom = capital, changeMap = "right" },   
		{ map="-25,-36", custom = capital, changeMap = "right" },   
		{ map="-25,-35", custom = capital, changeMap = "right" },   
		{ map="-24,-36", custom = capital, changeMap = "right" },   
		{ map="-23,-36", custom = capital, changeMap = "right" },   
		{ map="-22,-36", custom = capital, changeMap = "right" },   
		{ map="-21,-36", custom = capital, changeMap = "right" },   
		{ map="-18,-36", custom = capital, changeMap = "right" },   
		{ map="-18,-34", custom = capital, changeMap = "right" },  
		{ map="-18,-33", custom = capital, changeMap = "right" },   
		{ map="-18,-35", custom = capital, changeMap = "right" },   
		{ map="-19,-35", custom = capital, changeMap = "right" },   
		{ map="-19,-34", custom = capital, changeMap = "right" },   
		{ map="-19,-33", custom = capital, changeMap = "right" },   
		{ map="-19,-32", custom = capital, changeMap = "right" },   
		{ map="-19,-31", custom = capital, changeMap = "right" },   
		{ map="-19,-30", custom = capital, changeMap = "right" },   
		{ map="-18,-31", custom = capital, changeMap = "right" },  
		{ map="-18,-30", custom = capital, changeMap = "right" },  
		{ map="-18,-32", custom = capital, changeMap = "right" },   
		{ map="-18,-28", custom = capital, changeMap = "right" },  
		{ map="-18,-29", custom = capital, changeMap = "right" },  
		{ map="-19,-29", custom = capital, changeMap = "right" },   
		{ map="-19,-27", custom = capital, changeMap = "right" },   
		{ map="-19,-28", custom = capital, changeMap = "right" },   
		{ map="-19,-26", custom = capital, changeMap = "right" },   
		{ map="-19,-25", custom = capital, changeMap = "right" },   
		{ map="-19,-24", custom = capital, changeMap = "right" },   
		{ map="-19,-23", custom = capital, changeMap = "right" },   
		{ map="-19,-22", custom = capital, changeMap = "right" },   
		{ map="-19,-20", custom = capital, changeMap = "right" },   
		{ map="-19,-21", custom = capital, changeMap = "right" },   
		{ map="-20,-21", custom = capital, changeMap = "right" },  
		{ map="-21,-21", custom = capital, changeMap = "right" },   
		{ map="-21,-20", custom = capital, changeMap = "right" },   
		{ map="-21,-19", custom = capital, changeMap = "right" },   
		{ map="-21,-18", custom = capital, changeMap = "right" },   
		{ map="-21,-17", custom = capital, changeMap = "right" },   
		{ map="-21,-16", custom = capital, changeMap = "right" },   
		{ map="-19,-19", custom = capital, changeMap = "right" },   
		{ map="-19,-18", custom = capital, changeMap = "right" },   
		{ map="-19,-17", custom = capital, changeMap = "right" },   
		{ map="-19,-15", custom = capital, changeMap = "right" },   
		{ map="-19,-16", custom = capital, changeMap = "right" },   
		{ map="-19,-14", custom = capital, changeMap = "right" },   
		{ map="-20,-14", custom = capital, changeMap = "right" },   
		{ map="-20,-13", custom = capital, changeMap = "right" },   
		{ map="-21,-13", custom = capital, changeMap = "right" },   
		{ map="-21,-14", custom = capital, changeMap = "right" },   
		{ map="-22,-14", custom = capital, changeMap = "right" },  
		{ map="-22,-13", custom = capital, changeMap = "right" },  
		{ map="-23,-14", custom = capital, changeMap = "right" },  
		{ map="-23,-15", custom = capital, changeMap = "right" },  
		{ map="-24,-15", custom = capital, changeMap = "right" },  
		{ map="-24,-16", custom = capital, changeMap = "right" },  
		{ map="-24,-14", custom = capital, changeMap = "right" },  
		{ map="-24,-13", custom = capital, changeMap = "right" },  
		{ map="-22,-15", custom = capital, changeMap = "right" },  
		{ map="-21,-15", custom = capital, changeMap = "right" },   
		{ map="-22,-16", custom = capital, changeMap = "right" },  
		{ map="-23,-16", custom = capital, changeMap = "right" },  
		{ map="-20,-16", custom = capital, changeMap = "right" },   
		{ map="-20,-15", custom = capital, changeMap = "right" },   
		{ map="-20,-19", custom = capital, changeMap = "right" },   
		{ map="-20,-18", custom = capital, changeMap = "right" },   
		{ map="-20,-17", custom = capital, changeMap = "right" },   
		{ map="-22,-26", custom = capital, changeMap = "right" },   
		{ map="-22,-25", custom = capital, changeMap = "right" },   
		{ map="-22,-24", custom = capital, changeMap = "right" },   
		{ map="-22,-23", custom = capital, changeMap = "right" },   
		{ map="-22,-21", custom = capital, changeMap = "right" },   
		{ map="-22,-20", custom = capital, changeMap = "right" },   
		{ map="-22,-22", custom = capital, changeMap = "right" },   
		{ map="-21,-29", custom = capital, changeMap = "right" },   
		{ map="-21,-28", custom = capital, changeMap = "right" },   
		{ map="-21,-27", custom = capital, changeMap = "right" },   
		{ map="-21,-26", custom = capital, changeMap = "right" },   
		{ map="-21,-25", custom = capital, changeMap = "right" },   
		{ map="-21,-24", custom = capital, changeMap = "right" },   
		{ map="-21,-23", custom = capital, changeMap = "right" },   
		{ map="-22,-27", custom = capital, changeMap = "right" },   
		{ map="-20,-29", custom = capital, changeMap = "right" },   
		{ map="-20,-28", custom = capital, changeMap = "right" },   
		{ map="-20,-27", custom = capital, changeMap = "right" },   
		{ map="-20,-26", custom = capital, changeMap = "right" },   
		{ map="-20,-25", custom = capital, changeMap = "right" },   
		{ map="-20,-24", custom = capital, changeMap = "right" },   
		{ map="-20,-23", custom = capital, changeMap = "right" },   
		{ map="-20,-22", custom = capital, changeMap = "right" },   
		{ map="-21,-22", custom = capital, changeMap = "right" },   
		{ map="-20,-35", custom = capital, changeMap = "right" },   
		{ map="-20,-33", custom = capital, changeMap = "right" },   
		{ map="-20,-32", custom = capital, changeMap = "right" },   
		{ map="-20,-31", custom = capital, changeMap = "right" },   
		{ map="-20,-34", custom = capital, changeMap = "right" },   
		{ map="-20,-30", custom = capital, changeMap = "right" },   
		{ map="-26,-37", custom = capital, changeMap = "right" },   
		{ map="-25,-37", custom = capital, changeMap = "right" },   
		{ map="-24,-37", custom = capital, changeMap = "right" },   
		{ map="-23,-37", custom = capital, changeMap = "right" },   
		{ map="-22,-37", custom = capital, changeMap = "right" },   
		{ map="-21,-37", custom = capital, changeMap = "right" },   
		{ map="-20,-37", custom = capital, changeMap = "right" },   
		{ map="-19,-37", custom = capital, changeMap = "right" },   
		{ map="-18,-37", custom = capital, changeMap = "right" },   
		{ map="-19,-36", custom = capital, changeMap = "right" },   
		{ map="-20,-36", custom = capital, changeMap = "right" },   
		{ map="-19,-13", custom = capital, changeMap = "right" },   
		{ map="-19,-12", custom = capital, changeMap = "right" },  
		{ map="-20,-12", custom = capital, changeMap = "right" },  
		{ map="-21,-12", custom = capital, changeMap = "right" },  
		{ map="-22,-12", custom = capital, changeMap = "right" },  
		{ map="-23,-12", custom = capital, changeMap = "right" },  
		{ map="-24,-12", custom = capital, changeMap = "right" },  
		{ map="-30,-19", custom = capital, changeMap = "right" },   
		{ map="-30,-20", custom = capital, changeMap = "right" },   
		{ map="-30,-21", custom = capital, changeMap = "right" },   
		{ map="-30,-22", custom = capital, changeMap = "right" },   
		{ map="-30,-24", custom = capital, changeMap = "right" },   
		{ map="-30,-25", custom = capital, changeMap = "right" },   
		{ map="-30,-27", custom = capital, changeMap = "right" },   
		{ map="-30,-28", custom = capital, changeMap = "right" },   
		{ map="-30,-26", custom = capital, changeMap = "right" },   
		{ map="-30,-23", custom = capital, changeMap = "right" },   
		{ map="-30,-29", custom = capital, changeMap = "right" },   
		{ map="-30,-30", custom = capital, changeMap = "right" },   
		{ map="-29,-30", custom = capital, changeMap = "right" },   
		{ map="-29,-29", custom = capital, changeMap = "right" },   
		{ map="-27,-29", custom = capital, changeMap = "right" }, 
		{ map="-27,-30", custom = capital, changeMap = "right" }, 
		{ map="-27,-31", custom = capital, changeMap = "right" },
		{ map="-27,-32", custom = capital, changeMap = "right" },
		{ map="-27,-33", custom = capital, changeMap = "right" },
		{ map="-26,-34", custom = capital, changeMap = "right" }, 
		{ map="-25,-34", custom = capital, changeMap = "right" }, 
		{ map="-23,-13", custom = capital, changeMap = "right" }, 
		{ map="-27,-21", custom = capital, changeMap = "right" }, 
		{ map="-26,-33", custom = capital, changeMap = "right" }, 
		{ map="-26,-32", custom = capital, changeMap = "right" }, 
		{ map="-26,32", custom = capital, changeMap = "right" }, 
		{ map="-26,29", custom = capital, changeMap = "right" }, 
		{ map="-26,31", custom = capital, changeMap = "right" }, 
		

		





	}
end
