---------------------------------------------------
-- Auteur: Nelphegan
-- Zone : Astrub [Fôret][Champs]+[Bank]
-- Métier: [Alchimiste]
-- Départ: Banque
---------------------------------------------------
MAX_PODS = 95 -- A 95% des pods votre bots va vider à la Banque
ELEMENTS_TO_GATHER = { 66, 67, 254, 255 } -- Éléments à récolter ({} = tous)
OPEN_BAGS = false -- Ouverture automatique des sacs 
DISPLAY_GATHER_COUNT = true -- Affiche le compteur des récoltes
---------------------------------------------------

-- Fonction move obligatoire
function move()
	return {
	{ map="4,-17", changeMap="top" },
	{ map="4,-18", changeMap="top" },
	{ map="4,-19", changeMap="top" },
	{ map="4,-20", changeMap="top" },
	{ map="4,-21", changeMap="top" },
	{ map="4,-22", changeMap="right" },
	{ map="5,-22", changeMap="top" },
	{ map="5,-23", changeMap="left" },
	{ map="4,-23", changeMap="left" },
	{ map="3,-23", gather = true, changeMap="left" },
	{ map="2,-23", gather = true, changeMap="top" },
	{ map="2,-24", gather = true, changeMap="top" },
	{ map="2,-25", changeMap="left" },
	{ map="1,-25", gather = true, changeMap="left" },
	{ map="0,-25", gather = true, changeMap="top" },
	{ map="0,-26", gather = true, changeMap="top" },
	{ map="0,-27", gather = true, changeMap="right" },
	{ map="1,-27", gather = true, changeMap="bottom" },
	{ map="1,-26", gather = true, changeMap="bottom" },
	{ map="1,-25", gather = true, changeMap="right" },
	{ map="2,-25", changeMap="top" },
	{ map="2,-26", gather = true, changeMap="top" },
	{ map="2,-27", gather = true, changeMap="top" },
	{ map="2,-28", gather = true, changeMap="right" },
	{ map="3,-28", gather = true, changeMap="top" },
	{ map="3,-29", changeMap="right" },
	{ map="4,-29", gather = true, changeMap="bottom" },
	{ map="4,-28", changeMap="bottom" },
	{ map="4,-27", gather = true, changeMap="bottom" },
	{ map="4,-26", changeMap="bottom" },
	{ map="4,-25", gather = true, changeMap="bottom" },
	{ map="4,-24", gather = true, changeMap="right" },
	{ map="5,-24", gather = true, changeMap="top" },
	{ map="5,-25", gather = true, changeMap="top" },
	{ map="5,-26", gather = true, changeMap="top" },
	{ map="5,-27", changeMap="top" },
	{ map="5,-28", gather = true, changeMap="top" },
	{ map="5,-29", gather = true, changeMap="top" },
	{ map="5,-30", gather = true, changeMap="right" },
	{ map="6,-30", gather = true, changeMap="bottom" },
	{ map="6,-29", gather = true, changeMap="bottom" },
	{ map="6,-28", gather = true, changeMap="bottom" },
	{ map="6,-27", gather = true, changeMap="right" },
	{ map="7,-27", gather = true, changeMap="bottom" },
	{ map="7,-26", gather = true, changeMap="left" },
	{ map="6,-26", gather = true, changeMap="bottom" },
	{ map="6,-25", gather = true, changeMap="bottom" },
	{ map="6,-24", changeMap="right" },
	{ map="7,-24", changeMap="right" },
	{ map="8,-24", gather = true, changeMap="top" },
	{ map="8,-25", gather = true, changeMap="right" },
	{ map="9,-25", gather = true, changeMap="bottom" },
	{ map="9,-24", gather = true, changeMap="bottom" },
	{ map="9,-23", changeMap="left" },
	{ map="8,-23", changeMap="left" },
	{ map="7,-23", gather = true, changeMap="left" },
	{ map="6,-23", gather = true, changeMap="left" },
	{ map="5,-23", changeMap="left" },
	{ map = "84674566", changeMap = "top" },    -- Map exterieure de la banque
    { map = "83887104", changeMap = "396" },    -- Map interieure de la banque
  }
end

function bank ()
	return {
	{ map="4,-17", changeMap="bottom" },
	{ map="4,-18", changeMap="bottom" },
	{ map="4,-19", changeMap="bottom" },
	{ map="4,-20", changeMap="bottom" },
	{ map="4,-21", changeMap="bottom" },
	{ map="5,-21", changeMap="left" },
	{ map="5,-22", changeMap="bottom" },
	{ map="5,-23", changeMap="bottom" },
	{ map="1,-25", changeMap="right" },
	{ map="0,-25", changeMap="right" },
	{ map="1,-26", changeMap="right" },
	{ map="0,-26", changeMap="right" },
	{ map="1,-27", changeMap="right" },
	{ map="0,-27", changeMap="right" },
	{ map="4,-23", changeMap="right" },
	{ map="3,-23", changeMap="right" },
	{ map="2,-23", changeMap="right" },
	{ map="2,-24", changeMap="bottom" },
	{ map="2,-25", changeMap="bottom" },
	{ map="2,-26", changeMap="bottom" },
	{ map="2,-27", changeMap="bottom" },
	{ map="2,-28", changeMap="bottom" },	
	{ map="3,-25", changeMap="right" },
	{ map="3,-26", changeMap="right" },
	{ map="3,-28", changeMap="right" },	
	{ map="4,-24", changeMap="bottom" },
	{ map="4,-25", changeMap="bottom" },
	{ map="4,-26", changeMap="bottom" },
	{ map="4,-27", changeMap="bottom" },
	{ map="4,-28", changeMap="bottom" },
	{ map="4,-29", changeMap="bottom" },	
	{ map="5,-30", changeMap="bottom" },
	{ map="5,-29", changeMap="bottom" },
	{ map="5,-28", changeMap="bottom" },
	{ map="5,-27", changeMap="bottom" },
	{ map="5,-26", changeMap="bottom" },
	{ map="5,-25", changeMap="left" },
	{ map="5,-24", changeMap="bottom" },
	{ map="6,-30", changeMap="bottom" },
	{ map="6,-29", changeMap="bottom" },
	{ map="6,-28", changeMap="bottom" },
	{ map="6,-27", changeMap="bottom" },
	{ map="7,-27", changeMap="left" },
	{ map="7,-26", changeMap="left" },
	{ map="6,-26", changeMap="bottom" },
	{ map="6,-25", changeMap="bottom" },
	{ map="6,-24", changeMap="bottom" },
	{ map="7,-24", changeMap="left" },
	{ map="8,-24", changeMap="left" },
	{ map="8,-25", changeMap="bottom" },
	{ map="9,-25", changeMap="left" },
	{ map="9,-24", changeMap="left" },
	{ map="9,-23", changeMap="left" },
	{ map="8,-23", changeMap="left" },
	{ map="7,-23", changeMap="left" },
	{ map="6,-23", changeMap="left" },
	{ map = "84674566", door = "303" }, -- Map exterieure de la banque
    { map = "83887104", npcBank = true }, -- Parle au pnj et vide son inventaire en banque
	}
end
	