---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur :
-- Type :
-- Zone :
---------------------------------------------

MAX_PODS = 90
OPEN_BAGS = true
BANK_GET_KAMAS = 0
ELEMENTS_TO_GATHER = {34 , 8, 98} -- Nogueira, Carvalho, Bombu
DISPLAY_GATHER_COUNT = true

AUTO_DELETE = {  }

function move()
	return {
		{ map="-25,-34", gather = true, changeMap = "left" },
		{ map="-26,-34", gather = true, changeMap = "left" },
		{ map="-27,-34", gather = true, changeMap = "left" },
		{ map="-28,-34", gather = true, changeMap = "bottom" },
		{ map="-28,-33", changeMap = "right" },
		{ map="-27,-33", gather = true, changeMap = "right" },
		{ map="-26,-33", gather = true, changeMap = "bottom" },
		{ map="-26,-32", gather = true, changeMap = "left" },
		{ map="-27,-32", gather = true, changeMap = "bottom" },
		{ map="-27,-31", gather = true, changeMap = "bottom" },
		{ map="-27,-30", gather = true, changeMap = "left" },
		{ map="-28,-30", gather = true, changeMap = "left" },
		{ map="-29,-30", changeMap = "bottom" },
		{ map="-29,-29", gather = true, changeMap = "right" },
		{ map="-28,-29", gather = true, changeMap = "right" },
		{ map="-27,-29", gather = true, changeMap = "bottom" },
		{ map="-27,-28", gather = true, changeMap = "left" },
		{ map="-28,-28", gather = true, changeMap = "left" },
		{ map="-29,-28", gather = true, changeMap = "bottom" },
		{ map="-29,-27", gather = true, changeMap = "bottom" },
		{ map="-29,-26", gather = true, changeMap = "bottom" },
		{ map="-29,-25", changeMap = "right" },
		{ map="-28,-25", gather = true, changeMap = "bottom" },
		{ map="-28,-24", gather = true, changeMap = "left" },
		{ map="-29,-24", gather = true, changeMap = "bottom" },
		{ map="-29,-23", gather = true, changeMap = "bottom" },
		{ map="-29,-22", gather = true, changeMap = "bottom" },
		{ map="-29,-21", gather = true, changeMap = "right" },
		{ map="-28,-21", gather = true, changeMap = "bottom" },
		{ map="-28,-20", gather = true, changeMap = "right" },
		{ map="-27,-20", gather = true, changeMap = "bottom" },
		{ map="-27,-19", gather = true, changeMap = "left" },
		{ map="-28,-19", gather = true, changeMap = "bottom" },
		{ map="-28,-18", gather = true, changeMap = "right" },
		{ map="-27,-18", gather = true, changeMap = "bottom" },
		{ map="-27,-17", gather = true, changeMap = "right" },
		{ map="-26,-17", gather = true, changeMap = "bottom" },
		{ map="-26,-16", gather = true, changeMap = "bottom" },
		{ map="-26,-15", gather = true, changeMap = "bottom" },
		{ map="-26,-14", gather = true, changeMap = "left" },
		{ map="-27,-14", gather = true, changeMap = "left" },
		{ map="-28,-14", gather = true, changeMap = "bottom" },
		{ map="-28,-13", gather = true, changeMap = "bottom" },
		{ map="-28,-12", gather = true, changeMap = "right" },
		{ map="-27,-12", gather = true, changeMap = "right" },
		{ map="-26,-12", gather = true, changeMap = "right" },
		{ map="-25,-12", gather = true, changeMap = "right" },
		{ map="-24,-12", gather = true, changeMap = "right" },
		{ map="-23,-12", gather = true, changeMap = "top" },
		{ map="-23,-13", gather = true, changeMap = "top" },
		{ map="-23,-14", changeMap = "top" },
		{ map="-23,-15", gather = true, changeMap = "right" },
		{ map="-22,-15", gather = true, changeMap = "bottom" },
		{ map="-22,-14", gather = true, changeMap = "right" },
		{ map="-21,-14", changeMap = "top" },
		{ map="-21,-15", gather = true, changeMap = "right" },
		{ map="-20,-15", gather = true, changeMap = "top" },
		{ map="-20,-16", changeMap = "top" },
		{ map="-20,-17", gather = true, changeMap = "right" },
		{ map="-19,-17", gather = true, changeMap = "right" },
		{ map="-18,-17", gather = true, changeMap = "right" },
		{ map="-17,-17", gather = true, changeMap = "right" },
		{ map="-16,-17", gather = true, changeMap = "right" },
		{ map="-15,-17", gather = true, changeMap = "right" },
		{ map="-14,-17", gather = true, changeMap = "right" },
		{ map="-13,-17", gather = true, changeMap = "right" },
		{ map="-12,-17", gather = true, changeMap = "right" },
		{ map="-11,-17", changeMap = "top" },
		{ map="-11,-18", gather = true, changeMap = "top" },
		{ map="-11,-19", changeMap = "left" },
		{ map="-12,-19", gather = true, changeMap = "bottom" },
		{ map="-12,-18", changeMap = "left" },
		{ map="-13,-18", gather = true, changeMap = "left" },
		{ map="-14,-18", changeMap = "top" },
		{ map="-14,-19", gather = true, changeMap = "top" },
		{ map="-14,-20", gather = true, changeMap = "left" },
		{ map="-15,-20", gather = true, changeMap = "bottom" },
		{ map="-15,-19", gather = true, changeMap = "left" },
		{ map="-16,-19", gather = true, changeMap = "top" },
		{ map="-16,-20", gather = true, changeMap = "left" },
		{ map="-17,-20", changeMap = "bottom" },
		{ map="-17,-19", changeMap = "bottom" },
		{ map="-17,-18", gather = true, changeMap = "left" },
		{ map="-18,-18", gather = true, changeMap = "left" },
		{ map="-19,-18", gather = true, changeMap = "top" },
		{ map="-19,-19", gather = true, changeMap = "top" },
		{ map="-19,-20", gather = true, changeMap = "top" },
		{ map="-19,-23", gather = true, changeMap = "top" },
		{ map="-19,-24", gather = true, changeMap = "left" },
		{ map="-20,-25", gather = true, changeMap = "top" },
		{ map="-20,-28", gather = true, changeMap = "top" },
		{ map="-20,-29", gather = true, changeMap = "top" },
		{ map="-20,-30", gather = true, changeMap = "top" },
		{ map="-20,-31", changeMap = "right" },
		{ map="-19,-31", changeMap = "right" },
		{ map="-18,-31", gather = true, changeMap = "top" },
		{ map="-18,-32", changeMap = "top" },
		{ map="-18,-33", changeMap = "left" },
		{ map="-19,-33", gather = true, changeMap = "top" },
		{ map="-19,-34", gather = true, changeMap = "right" },
		{ map="-18,-34", gather = true, changeMap = "top" },
		{ map="-18,-35", gather = true, changeMap = "top" },
		{ map="-18,-36", gather = true, changeMap = "top" },
		{ map="-18,-37", changeMap = "left" },
		{ map="-19,-37", gather = true, changeMap = "left" },
		{ map="-20,-37", gather = true, changeMap = "left" },
		{ map="-21,-37", changeMap = "bottom" },
		{ map="-21,-36", changeMap = "left" },
		{ map="-22,-36", changeMap = "left" },
		{ map="-23,-36", changeMap = "left" },
		{ map="-24,-36", changeMap = "bottom" },
		{ map="-24,-35", changeMap = "left" },
		{ map="-25,-35", changeMap = "bottom" },
		{ map="-20,-20", changeMap = "right" },
		{ map="-19,-21", changeMap = "top" },
		{ map="-19,-22", changeMap = "top" },
		{ map="-20,-24", changeMap = "top" },
		{ map="-20,-27", changeMap = "top" },
		{ map="-20,-26", changeMap = "top" },
		{ map="-27,-36", changeMap = "bottom" },
		{ map="-27,-35", changeMap = "right" },
		{ map="-26,-35", changeMap = "right" },
		{ map="-27,-37", changeMap = "bottom" },
		{ map="-27,-38", changeMap = "bottom" },
		{ map="-27,-39", changeMap = "bottom" },
		{ map="-27,-40", changeMap = "bottom" },
		{ map="-27,-41", changeMap = "bottom" },
		{ map="-27,-42", changeMap = "bottom" },
		{ map="-27,-43", changeMap = "bottom" },
		{ map="-28,-43", changeMap = "right" },
		{ map="-29,-43", changeMap = "right" },
		{ map="-29,-44", changeMap = "bottom" },
		{ map="-29,-45", changeMap = "bottom" },
		{ map="-29,-46", changeMap = "bottom" },
		{ map="-29,-47", changeMap = "bottom" },
		{ map="-29,-48", changeMap = "bottom" },
		{ map="-29,-49", changeMap = "bottom" },
		{ map="-29,-50", changeMap = "bottom" },
		{ map="-29,-51", changeMap = "bottom" },
		{ map="-29,-52", changeMap = "bottom" },
		{ map="-29,-53", changeMap = "bottom" },
		{ map="-29,-54", changeMap = "bottom" },
		{ map="-30,-54", changeMap = "right" },
		{ map = "147254", changeMap = "right" },
		{ map = "2885641", changeMap = "424" },
	}
end

function bank()
	return {
		{ map="-25,-34", changeMap = "top" },
		{ map="-26,-34", changeMap = "right" },
		{ map="-27,-34", changeMap = "right" },
		{ map="-28,-34", changeMap = "right" },
		{ map="-28,-33", changeMap = "top" },
		{ map="-27,-33", changeMap = "top" },
		{ map="-26,-33", changeMap = "top" },
		{ map="-26,-32", changeMap = "top" },
		{ map="-27,-32", changeMap = "right" },
		{ map="-27,-31", changeMap = "top" },
		{ map="-27,-30", changeMap = "top" },
		{ map="-28,-30", changeMap = "right" },
		{ map="-29,-30", changeMap = "right" },
		{ map="-29,-29", changeMap = "top" },
		{ map="-28,-29", changeMap = "right|top" },
		{ map="-27,-29", changeMap = "top" },
		{ map="-27,-28", changeMap = "top" },
		{ map="-28,-28", changeMap = "right|top" },
		{ map="-29,-28", changeMap = "top" },
		{ map="-29,-27", changeMap = "top" },
		{ map="-29,-26", changeMap = "top" },
		{ map="-29,-25", changeMap = "top" },
		{ map="-28,-25", changeMap = "left" },
		{ map="-28,-24", changeMap = "top|left" },
		{ map="-29,-24", changeMap = "top" },
		{ map="-29,-23", changeMap = "top" },
		{ map="-29,-22", changeMap = "top" },
		{ map="-29,-21", changeMap = "top" },
		{ map="-28,-21", changeMap = "left" },
		{ map="-28,-20", changeMap = "top" },
		{ map="-27,-20", changeMap = "left" },
		{ map="-27,-19", changeMap = "left" },
		{ map="-28,-19", changeMap = "top" },
		{ map="-28,-18", changeMap = "top" },
		{ map="-27,-18", changeMap = "left" },
		{ map="-27,-17", changeMap = "top" },
		{ map="-26,-17", changeMap = "left" },
		{ map="-26,-16", changeMap = "top" },
		{ map="-26,-15", changeMap = "top" },
		{ map="-26,-14", changeMap = "top" },
		{ map="-27,-14", changeMap = "right" },
		{ map="-28,-14", changeMap = "right" },
		{ map="-28,-13", changeMap = "top" },
		{ map="-28,-12", changeMap = "top" },
		{ map="-27,-12", changeMap = "left" },
		{ map="-26,-12", changeMap = "left" },
		{ map="-25,-12", changeMap = "left" },
		{ map="-24,-12", changeMap = "left" },
		{ map="-23,-12", changeMap = "left" },
		{ map="-23,-13", changeMap = "bottom" },
		{ map="-23,-14", changeMap = "bottom" },
		{ map="-23,-15", changeMap = "bottom" },
		{ map="-22,-15", changeMap = "left" },
		{ map="-22,-14", changeMap = "left" },
		{ map="-21,-14", changeMap = "left" },
		{ map="-21,-15", changeMap = "left" },
		{ map="-20,-15", changeMap = "left" },
		{ map="-20,-16", changeMap = "bottom" },
		{ map="-20,-17", changeMap = "bottom" },
		{ map="-19,-17", changeMap = "left" },
		{ map="-18,-17", changeMap = "left" },
		{ map="-17,-17", changeMap = "left" },
		{ map="-16,-17", changeMap = "left" },
		{ map="-15,-17", changeMap = "left" },
		{ map="-14,-17", changeMap = "left" },
		{ map="-13,-17", changeMap = "left" },
		{ map="-12,-17", changeMap = "left" },
		{ map="-11,-17", changeMap = "top" },
		{ map="-11,-18", changeMap = "top" },
		{ map="-11,-19", changeMap = "left" },
		{ map="-12,-19", changeMap = "bottom" },
		{ map="-12,-18", changeMap = "left" },
		{ map="-13,-18", changeMap = "left" },
		{ map="-14,-18", changeMap = "top" },
		{ map="-14,-19", changeMap = "top" },
		{ map="-14,-20", changeMap = "left" },
		{ map="-15,-20", changeMap = "bottom" },
		{ map="-15,-19", changeMap = "left" },
		{ map="-16,-19", changeMap = "top" },
		{ map="-16,-20", changeMap = "left" },
		{ map="-17,-20", changeMap = "bottom" },
		{ map="-17,-19", changeMap = "bottom" },
		{ map="-17,-18", changeMap = "left" },
		{ map="-18,-18", changeMap = "left" },
		{ map="-19,-18", changeMap = "top" },
		{ map="-19,-19", changeMap = "top" },
		{ map="-19,-20", changeMap = "top" },
		{ map="-19,-23", changeMap = "top" },
		{ map="-19,-24", changeMap = "left" },
		{ map="-20,-25", changeMap = "top" },
		{ map="-20,-28", changeMap = "top" },
		{ map="-20,-29", changeMap = "top" },
		{ map="-20,-30", changeMap = "top" },
		{ map="-20,-31", changeMap = "right" },
		{ map="-19,-31", changeMap = "right" },
		{ map="-18,-31", changeMap = "top" },
		{ map="-18,-32", changeMap = "top" },
		{ map="-18,-33", changeMap = "left" },
		{ map="-19,-33", changeMap = "top" },
		{ map="-19,-34", changeMap = "right" },
		{ map="-18,-34", changeMap = "top" },
		{ map="-18,-35", changeMap = "top" },
		{ map="-18,-36", changeMap = "top" },
		{ map="-18,-37", changeMap = "left" },
		{ map="-19,-37", changeMap = "left" },
		{ map="-20,-37", changeMap = "left" },
		{ map="-21,-37", changeMap = "bottom" },
		{ map="-21,-36", changeMap = "left" },
		{ map="-22,-36", changeMap = "left" },
		{ map="-23,-36", changeMap = "left" },
		{ map="-24,-36", changeMap = "bottom" },
		{ map="-24,-35", changeMap = "left" },
		{ map="-25,-35", changeMap = "left" },
		{ map="-19,-21", changeMap = "top" },
		{ map="-19,-22", changeMap = "top" },
		{ map="-20,-24", changeMap = "top" },
		{ map="-20,-27", changeMap = "top" },
		{ map="-20,-26", changeMap = "top" },
		{ map="-27,-36", changeMap = "top" },
		{ map="-27,-35", changeMap = "top" },
		{ map="-26,-35", changeMap = "left" },
		{ map="-27,-37", changeMap = "top" },
		{ map="-27,-38", changeMap = "top" },
		{ map="-27,-39", changeMap = "top" },
		{ map="-27,-40", changeMap = "top" },
		{ map="-27,-41", changeMap = "top" },
		{ map="-27,-42", changeMap = "top" },
		{ map="-27,-43", changeMap = "left" },
		{ map="-28,-43", changeMap = "left" },
		{ map="-29,-43", changeMap = "top" },
		{ map="-29,-44", changeMap = "top" },
		{ map="-29,-45", changeMap = "top" },
		{ map="-29,-46", changeMap = "top" },
		{ map="-29,-47", changeMap = "top" },
		{ map="-29,-48", changeMap = "top" },
		{ map="-29,-49", changeMap = "top" },
		{ map="-29,-50", changeMap = "top" },
		{ map="-29,-51", changeMap = "top" },
		{ map="-29,-52", changeMap = "top" },
		{ map="-29,-53", changeMap = "top" },
		{ map="-29,-54", changeMap = "left" },
		{ map="-30,-54", changeMap = "left" },
		{ map = "147254", door = "383" },
		{ map = "2885641", npcBank = true },
	}
end
