---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur :
-- Type :
-- Zone :
---------------------------------------------

MAX_PODS = 90
OPEN_BAGS = true

BANK_GET_KAMAS = 0
ELEMENTS_TO_GATHER = { }
DISPLAY_GATHER_COUNT = true

AUTO_DELETE = {  }

function move()
	return {
		{ map="-27,8", gather = true, changeMap = "bottom" },
		{ map="-27,9", gather = true, changeMap = "bottom" },
		{ map="-27,10", gather = true, changeMap = "bottom" },
		{ map="-27,11", gather = true, changeMap = "right" },
		{ map="-26,11", gather = true, changeMap = "bottom" },
		{ map="-27,12", gather = true, changeMap = "bottom" },
		{ map="-26,13", gather = true, changeMap = "bottom" },
		{ map="-27,14", gather = true, changeMap = "bottom" },
		{ map="-27,15", gather = true, changeMap = "bottom" },
		{ map="-26,12", gather = true, changeMap = "left" },
		{ map="-27,13", gather = true, changeMap = "right" },
		{ map="-26,14", gather = true, changeMap = "left" },
		{ map="-27,16", changeMap = "right" },
		{ map="-26,16", changeMap = "right" },
		{ map="-25,16", changeMap = "right" },
		{ map="-24,16", changeMap = "right" },
		{ map="-23,16", changeMap = "bottom" },
		{ map="-23,17", changeMap = "bottom" },
		{ map="-23,18", changeMap = "right" },
		{ map="-22,18", changeMap = "right" },
		{ map="-21,18", changeMap = "bottom" },
		{ map="-26,8", changeMap = "left" },
		{ map="-25,8", changeMap = "left" },
		{ map="-24,8", changeMap = "left" },
		{ map="-24,9", changeMap = "top" },
		{ map="-24,10", changeMap = "top" },
		{ map="-24,11", changeMap = "top" },
		{ map="-24,12", changeMap = "top" },
		{ map="-24,13", changeMap = "top" },
		{ map="-24,14", changeMap = "top" },
		{ map="-24,15", changeMap = "top" },
		{ map="-23,15", changeMap = "left" },
		{ map="-22,15", changeMap = "left" },
		{ map="-21,15", changeMap = "left" },
		{ map="-21,16", changeMap = "top" },
		{ map="-20,16", changeMap = "left" },
		{ map="-18,27", gather = true, changeMap = "top" },
		{ map="-18,26", gather = true, changeMap = "top" },
		{ map="-18,25", gather = true, changeMap = "top" },
		{ map="-18,24", gather = true, changeMap = "top" },
		{ map="-18,23", gather = true, changeMap = "top" },
		{ map="-18,22", gather = true, changeMap = "left" },
		{ map="-19,22", gather = true, changeMap = "left" },
		{ map="-19,23", gather = true, changeMap = "bottom" },
		{ map="-19,24", gather = true, changeMap = "bottom" },
		{ map="-19,25", gather = true, changeMap = "bottom" },
		{ map="-19,26", gather = true, changeMap = "left" },
		{ map="-20,26", gather = true, changeMap = "left" },
		{ map="-21,26", gather = true, changeMap = "left" },
		{ map="-22,26", gather = true, changeMap = "left" },
		{ map="-23,26", gather = true, changeMap = "left" },
		{ map="-24,26", gather = true, changeMap = "left" },
		{ map="-25,26", gather = true, changeMap = "left" },
		{ map="-26,26", gather = true, changeMap = "bottom" },
		{ map="-26,27", gather = true, changeMap = "right" },
		{ map="-21,19", changeMap = "bottom" },
		{ map="-21,20", changeMap = "bottom" },
		{ map="-21,21", changeMap = "bottom" },
		{ map="-21,22", changeMap = "bottom" },
		{ map="-21,23", changeMap = "right" },
		{ map="-20,23", changeMap = "right" },
		{ map="-20,22", changeMap = "top" },
		{ map="-20,21", changeMap = "top" },
		{ map="-20,20", changeMap = "top" },
		{ map="-20,19", changeMap = "top" },
		{ map="-20,18", changeMap = "top" },
		{ map="-20,17", changeMap = "top" },
		{ map="-25,27", changeMap = "right" },
		{ map="-24,27", gather = true, changeMap = "right" },
		{ map="-23,27", changeMap = "right" },
		{ map="-22,27", changeMap = "right" },
		{ map="-21,27", changeMap = "right" },
		{ map="-20,27", changeMap = "right" },
		{ map="-19,27", changeMap = "right" },
		{ map="-26,35", changeMap = "top" },
		{ map="-26,31", door = "125" },
		{ map="-26,32", changeMap = "top" },
		{ map="-26,33", changeMap = "top" },
		{ map="-26,34", changeMap = "top" },
		{ map="-25,29", changeMap = "top" },
		{ map="-25,28", changeMap = "top" },
		{ map = "144931", changeMap = "right" },
		{ map="-25,30", changeMap = "top" },
		{ map = "8914959", changeMap = "424" },
	}
end

function bank()
	return {
		{ map="-25,30", door = "546" },
		{ map="-27,8", changeMap = "bottom" },
		{ map="-27,9", changeMap = "bottom" },
		{ map="-27,10", changeMap = "bottom" },
		{ map="-27,11", changeMap = "right" },
		{ map="-26,11", changeMap = "bottom" },
		{ map="-27,12", changeMap = "bottom" },
		{ map="-26,13", changeMap = "bottom" },
		{ map="-27,14", changeMap = "bottom" },
		{ map="-27,15", changeMap = "bottom" },
		{ map="-26,12", changeMap = "left" },
		{ map="-27,13", changeMap = "right" },
		{ map="-26,14", changeMap = "left" },
		{ map="-27,16", changeMap = "right" },
		{ map="-26,16", changeMap = "right" },
		{ map="-25,16", changeMap = "right" },
		{ map="-24,16", changeMap = "right" },
		{ map="-23,16", changeMap = "bottom" },
		{ map="-23,17", changeMap = "bottom" },
		{ map="-23,18", changeMap = "right" },
		{ map="-22,18", changeMap = "right" },
		{ map="-21,18", changeMap = "bottom" },
		{ map="-26,8", changeMap = "right" },
		{ map="-25,8", changeMap = "right" },
		{ map="-24,8", changeMap = "bottom" },
		{ map="-24,9", changeMap = "bottom" },
		{ map="-24,10", changeMap = "bottom" },
		{ map="-24,11", changeMap = "bottom" },
		{ map="-24,12", changeMap = "bottom" },
		{ map="-24,13", changeMap = "bottom" },
		{ map="-24,14", changeMap = "bottom" },
		{ map="-24,15", changeMap = "right" },
		{ map="-23,15", changeMap = "right" },
		{ map="-22,15", changeMap = "right" },
		{ map="-21,15", changeMap = "bottom" },
		{ map="-21,16", changeMap = "right" },
		{ map="-20,16", changeMap = "bottom" },
		{ map="-18,27", changeMap = "left" },
		{ map="-18,26", changeMap = "bottom" },
		{ map="-18,25", changeMap = "bottom" },
		{ map="-18,24", changeMap = "bottom" },
		{ map="-18,23", changeMap = "bottom" },
		{ map="-18,22", changeMap = "bottom" },
		{ map="-19,22", changeMap = "right" },
		{ map="-19,23", changeMap = "bottom" },
		{ map="-19,24", changeMap = "bottom" },
		{ map="-19,25", changeMap = "bottom" },
		{ map="-19,26", changeMap = "left" },
		{ map="-20,26", changeMap = "left" },
		{ map="-21,26", changeMap = "left" },
		{ map="-22,26", changeMap = "bottom" },
		{ map="-23,26", changeMap = "bottom" },
		{ map="-24,26", changeMap = "bottom" },
		{ map="-25,26", changeMap = "bottom" },
		{ map="-26,26", changeMap = "right" },
		{ map="-26,27", changeMap = "right" },
		{ map="-21,19", changeMap = "bottom" },
		{ map="-21,20", changeMap = "bottom" },
		{ map="-21,21", changeMap = "bottom" },
		{ map="-21,22", changeMap = "bottom" },
		{ map="-21,23", changeMap = "right" },
		{ map="-20,23", changeMap = "right" },
		{ map="-20,22", changeMap = "right" },
		{ map="-20,21", changeMap = "bottom" },
		{ map="-20,20", changeMap = "bottom" },
		{ map="-20,19", changeMap = "bottom" },
		{ map="-20,18", changeMap = "bottom" },
		{ map="-20,17", changeMap = "bottom" },
		{ map="-25,27", changeMap = "bottom" },
		{ map="-24,27", changeMap = "left" },
		{ map="-23,27", changeMap = "left" },
		{ map="-22,27", changeMap = "left" },
		{ map="-21,27", changeMap = "left" },
		{ map="-20,27", changeMap = "left" },
		{ map="-19,27", changeMap = "left" },
		{ map="-26,35", changeMap = "left" },
		{ map="-26,32", changeMap = "bottom" },
		{ map="-26,33", changeMap = "bottom" },
		{ map="-26,34", changeMap = "bottom" },
		{ map="-26,31", changeMap = "bottom" },
		{ map="-25,29", changeMap = "bottom" },
		{ map="-25,28", changeMap = "bottom" },
		{ map = "144931", door = "262" },
		{ map = "8914959", npcBank = true },
	}
end
