---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur : athar85
-- Type : Récolte
-- Zone : Cania
-- Métier : Alchimiste
---------------------------------------------

MAX_PODS = 95
OPEN_BAGS = true

ELEMENTS_TO_GATHER = { }

AUTO_DELETE = {  }
DISPLAY_GATHER_COUNT = true
DISPLAY_BANK_COUNT = true

function move()
	return {
		{ map="-31,-53", changeMap = "bottom" },
		{ map="-31,-52", changeMap = "bottom" },
		{ map="-31,-51", changeMap = "bottom" },
		{ map="-31,-50", changeMap = "right" },
		{ map="-30,-50", changeMap = "right" },
		{ map="-29,-49", changeMap = "bottom" },
		{ map="-29,-50", changeMap = "bottom" },
		{ map="-29,-48", changeMap = "left" },
		{ map="-30,-48", gather = true, changeMap = "bottom" },
		{ map="-30,-47", gather = true, changeMap = "bottom" },
		{ map="-30,-46", changeMap = "left" },
		{ map="-31,-46", gather = true, changeMap = "top" },
		{ map="-31,-47", changeMap = "top" },
		{ map="-31,-48", changeMap = "left" },
		{ map="-32,-48", gather = true, changeMap = "top" },
		{ map="-32,-49", gather = true, changeMap = "left" },
		{ map="-33,-49", gather = true, changeMap = "bottom" },
		{ map="-33,-48", changeMap = "bottom" },
		{ map="-33,-47", changeMap = "bottom" },
		{ map="-33,-46", gather = true, changeMap = "right" },
		{ map="-32,-46", changeMap = "bottom" },
		{ map="-32,-45", changeMap = "right" },
		{ map="-31,-45", changeMap = "right" },
		{ map="-30,-45", changeMap = "right" },
		{ map="-29,-45", changeMap = "right" },
		{ map="-28,-45", changeMap = "right" },
		{ map="-27,-45", changeMap = "right" },
		{ map="-26,-46", gather = true, changeMap = "top" },
		{ map="-26,-45", changeMap = "top" },
		{ map="-23,-47", gather = true, changeMap = "right" },
		{ map="-22,-47", gather = true, changeMap = "right" },
		{ map="-21,-47", gather = true, changeMap = "bottom" },
		{ map="-21,-46", gather = true, changeMap = "bottom" },
		{ map="-22,-45", changeMap = "bottom" },
		{ map="-22,-44", gather = true, changeMap = "bottom" },
		{ map="-22,-43", gather = true, changeMap = "bottom" },
		{ map="-22,-42", changeMap = "bottom" },
		{ map="-22,-41", gather = true, changeMap = "right" },
		{ map="-21,-41", gather = true, changeMap = "top" },
		{ map="-21,-42", gather = true, changeMap = "right" },
		{ map="-20,-42", gather = true, changeMap = "right" },
		{ map="-19,-42", gather = true, changeMap = "right" },
		{ map="-18,-42", changeMap = "bottom" },
		{ map="-18,-41", gather = true, changeMap = "bottom" },
		{ map="-18,-40", gather = true, changeMap = "right" },
		{ map="-17,-40", gather = true, changeMap = "right" },
		{ map="-16,-40", gather = true, changeMap = "right" },
		{ map="-15,-40", gather = true, changeMap = "top" },
		{ map="-15,-41", gather = true, changeMap = "top" },
		{ map="-15,-42", gather = true, changeMap = "top" },
		{ map="-15,-43", changeMap = "right" },
		{ map="-14,-43", gather = true, changeMap = "right" },
		{ map="-13,-43", gather = true, changeMap = "right" },
		{ map="-12,-43", gather = true, changeMap = "bottom" },
		{ map="-12,-42", gather = true, changeMap = "right" },
		{ map="-11,-42", changeMap = "top" },
		{ map="-11,-43", changeMap = "top" },
		{ map="-11,-44", changeMap = "top" },
		{ map="-11,-45", changeMap = "top" }, 		
		{ map="-11,-46", changeMap = "top" },
		{ map="-11,-47", changeMap = "top" },
		{ map="-11,-48", changeMap = "left" },
		{ map="-12,-48", gather = true, changeMap = "left" },
		{ map="-13,-48", gather = true, changeMap = "bottom" },
		{ map="-13,-47", gather = true, changeMap = "left" },
		{ map="-14,-47", gather = true, changeMap = "left" },
		{ map="-15,-47", changeMap = "top" },
		{ map="-15,-48", changeMap = "top" },
		{ map="-15,-49", gather = true, changeMap = "left" },
		{ map="-16,-49", changeMap = "bottom" },
		{ map="-16,-48", gather = true, changeMap = "bottom" },
		{ map="-16,-46", gather = true, changeMap = "left" },
		{ map="-16,-47", changeMap = "bottom" },
		{ map="-17,-46", changeMap = "top" },
		{ map="-17,-47", gather = true, changeMap = "left" },
		{ map="-26,-47", gather = true, changeMap = "right" },
		{ map="-25,-47", changeMap = "right" },
		{ map="-24,-47", changeMap = "right" },
		{ map="-18,-47", changeMap = "top" },
		{ map="-18,-48", changeMap = "left" },
		{ map="-19,-48", changeMap = "left" },
		{ map="-20,-48", changeMap = "left" },
		{ map="-21,-48", changeMap = "left" },
		{ map="-22,-48", changeMap = "left" },
		{ map="-23,-48", changeMap = "left" },
		{ map="-24,-48", changeMap = "left" },
		{ map="-25,-48", changeMap = "left" },
		{ map="-26,-48", changeMap = "left" },
		{ map="-27,-48", changeMap = "left" },
		{ map="-28,-48", changeMap = "bottom" },
		{ map="-28,-47", changeMap = "left" },
		{ map="-29,-47", changeMap = "top" },
		{ map = "147254", changeMap = "bottom" },
		{ map="-21,-45", gather = true, changeMap = "left" },
		{ map = "2885641", changeMap = "424" },
	}
end

function bank()
	return {
		{ map="-31,-53", changeMap = "top" },
		{ map="-31,-52", changeMap = "top" },
		{ map="-31,-51", changeMap = "top" },
		{ map="-31,-50", changeMap = "top" },
		{ map="-30,-50", changeMap = "left" },
		{ map="-29,-49", changeMap = "top" },
		{ map="-29,-50", changeMap = "left" },
		{ map="-29,-48", changeMap = "top" },
		{ map="-30,-48", changeMap = "right" },
		{ map="-30,-47", changeMap = "right" },
		{ map="-30,-46", changeMap = "right" },
		{ map="-31,-46", changeMap = "right" },
		{ map="-31,-47", changeMap = "right" },
		{ map="-31,-48", changeMap = "right" },
		{ map="-32,-48", changeMap = "right" },
		{ map="-32,-49", changeMap = "bottom" },
		{ map="-33,-49", changeMap = "right" },
		{ map="-33,-48", changeMap = "right" },
		{ map="-33,-47", changeMap = "right" },
		{ map="-33,-46", changeMap = "right" },
		{ map="-32,-46", changeMap = "right" },
		{ map="-32,-45", changeMap = "right" },
		{ map="-31,-45", changeMap = "right" },
		{ map="-30,-45", changeMap = "right" },
		{ map="-29,-45", changeMap = "top" },
		{ map="-28,-45", changeMap = "left" },
		{ map="-27,-45", changeMap = "left" },
		{ map="-26,-46", changeMap = "left" },
		{ map="-26,-45", changeMap = "left" },
		{ map="-23,-47", changeMap = "left" },
		{ map="-22,-47", changeMap = "left" },
		{ map="-21,-47", changeMap = "left" },
		{ map="-21,-46", changeMap = "left" },
		{ map="-22,-45", changeMap = "left" },
		{ map="-22,-44", changeMap = "left" },
		{ map="-22,-43", changeMap = "left" },
		{ map="-22,-42", changeMap = "left" },
		{ map="-22,-41", changeMap = "left" },
		{ map="-21,-41", changeMap = "left" },
		{ map="-21,-42", changeMap = "left" },
		{ map="-20,-42", changeMap = "left" },
		{ map="-19,-42", changeMap = "left" },
		{ map="-18,-42", changeMap = "left" },
		{ map="-18,-41", changeMap = "left" },
		{ map="-18,-40", changeMap = "left" },
		{ map="-17,-40", changeMap = "left" },
		{ map="-16,-40", changeMap = "left" },
		{ map="-15,-40", changeMap = "left" },
		{ map="-15,-41", changeMap = "left" },
		{ map="-15,-42", changeMap = "left" },
		{ map="-15,-43", changeMap = "left" },
		{ map="-14,-43", changeMap = "left" },
		{ map="-13,-43", changeMap = "left" },
		{ map="-12,-43", changeMap = "left" },
		{ map="-12,-42", changeMap = "left" },
		{ map="-11,-42", changeMap = "left" },
		{ map="-11,-43", changeMap = "left" },
		{ map="-11,-44", changeMap = "left" },
		{ map="-11,-45", changeMap = "left" },
		{ map="-12,-45", changeMap = "left" },
		{ map="-12,-46", changeMap = "left" },
		{ map="-12,-47", changeMap = "left" },
		{ map="-12,-48", changeMap = "left" },
		{ map="-13,-48", changeMap = "left" },
		{ map="-13,-47", changeMap = "left" },
		{ map="-14,-47", changeMap = "left" },
		{ map="-15,-47", changeMap = "left" },
		{ map="-15,-48", changeMap = "left" },
		{ map="-15,-49", changeMap = "bottom" },
		{ map="-16,-49", changeMap = "bottom" },
		{ map="-16,-48", changeMap = "left" },
		{ map="-16,-46", changeMap = "left" },
		{ map="-16,-47", changeMap = "left" },
		{ map="-17,-46", changeMap = "left" },
		{ map="-17,-47", changeMap = "left" },
		{ map="-26,-47", changeMap = "left" },
		{ map="-25,-47", changeMap = "left" },
		{ map="-24,-47", changeMap = "left" },
		{ map="-18,-47", changeMap = "left" },
		{ map="-18,-48", changeMap = "left" },
		{ map="-19,-48", changeMap = "left" },
		{ map="-20,-48", changeMap = "left" },
		{ map="-21,-48", changeMap = "left" },
		{ map="-22,-48", changeMap = "left" },
		{ map="-23,-48", changeMap = "left" },
		{ map="-24,-48", changeMap = "left" },
		{ map="-25,-48", changeMap = "left" },
		{ map="-26,-48", changeMap = "left" },
		{ map="-27,-48", changeMap = "left" },
		{ map="-28,-48", changeMap = "left" },
		{ map="-21,-45", changeMap = "left" },
		{ map="-17,-48", changeMap = "left" },
		{ map="-14,-48", changeMap = "left" },
		{ map="-14,-42", changeMap = "left" },
		{ map="-13,-42", changeMap = "left" },
		{ map="-19,-40", changeMap = "left" },
		{ map="-20,-40", changeMap = "left" },
		{ map="-21,-40", changeMap = "left" },
		{ map="-22,-40", changeMap = "left" },
		{ map="-23,-40", changeMap = "left" },
		{ map="-24,-40", changeMap = "left" },
		{ map="-25,-40", changeMap = "left" },
		{ map="-26,-40", changeMap = "left" },
		{ map="-27,-40", changeMap = "left" },
		{ map="-28,-40", changeMap = "left" },
		{ map="-13,-46", changeMap = "left" },
		{ map="-14,-46", changeMap = "left" },
		{ map="-15,-46", changeMap = "left" },
		{ map="-19,-47", changeMap = "left" },
		{ map="-20,-47", changeMap = "left" },
		{ map="-27,-47", changeMap = "left" },
		{ map="-28,-47", changeMap = "left" },
		{ map="-28,-46", changeMap = "left" },
		{ map="-27,-46", changeMap = "left" },
		{ map="-25,-46", changeMap = "left" },
		{ map="-23,-46", changeMap = "left" },
		{ map="-24,-46", changeMap = "left" },
		{ map="-22,-46", changeMap = "left" },
		{ map="-20,-46", changeMap = "left" },
		{ map="-19,-46", changeMap = "left" },
		{ map="-18,-46", changeMap = "left" },
		{ map="-13,-45", changeMap = "left" },
		{ map="-13,-44", changeMap = "left" },
		{ map="-14,-44", changeMap = "left" },
		{ map="-14,-45", changeMap = "left" },
		{ map="-12,-44", changeMap = "left" },
		{ map="-15,-44", changeMap = "left" },
		{ map="-15,-45", changeMap = "left" },
		{ map="-16,-41", changeMap = "left" },
		{ map="-17,-41", changeMap = "left" },
		{ map="-19,-41", changeMap = "left" },
		{ map="-20,-41", changeMap = "left" },
		{ map="-23,-41", changeMap = "left" },
		{ map="-24,-41", changeMap = "left" },
		{ map="-25,-41", changeMap = "left" },
		{ map="-26,-41", changeMap = "left" },
		{ map="-27,-41", changeMap = "left" },
		{ map="-28,-41", changeMap = "left" },
		{ map="-28,-42", changeMap = "left" },
		{ map="-28,-43", changeMap = "left" },
		{ map="-28,-44", changeMap = "left" },
		{ map="-27,-44", changeMap = "left" },
		{ map="-27,-43", changeMap = "left" },
		{ map="-27,-42", changeMap = "left" },
		{ map="-26,-42", changeMap = "left" },
		{ map="-26,-43", changeMap = "left" },
		{ map="-26,-44", changeMap = "left" },
		{ map="-25,-45", changeMap = "left" },
		{ map="-25,-44", changeMap = "left" },
		{ map="-25,-43", changeMap = "left" },
		{ map="-25,-42", changeMap = "left" },
		{ map="-24,-42", changeMap = "left" },
		{ map="-24,-43", changeMap = "left" },
		{ map="-24,-44", changeMap = "left" },
		{ map="-24,-45", changeMap = "left" },
		{ map="-23,-45", changeMap = "left" },
		{ map="-23,-44", changeMap = "left" },
		{ map="-23,-43", changeMap = "left" },
		{ map="-23,-42", changeMap = "left" },
		{ map="-21,-44", changeMap = "left" },
		{ map="-21,-43", changeMap = "left" },
		{ map="-20,-43", changeMap = "left" },
		{ map="-20,-44", changeMap = "left" },
		{ map="-20,-45", changeMap = "left" },
		{ map="-19,-45", changeMap = "left" },
		{ map="-19,-44", changeMap = "left" },
		{ map="-19,-43", changeMap = "left" },
		{ map="-18,-43", changeMap = "left" },
		{ map="-18,-44", changeMap = "left" },
		{ map="-18,-45", changeMap = "left" },
		{ map="-17,-45", changeMap = "left" },
		{ map="-17,-44", changeMap = "left" },
		{ map="-17,-43", changeMap = "left" },
		{ map="-17,-42", changeMap = "left" },
		{ map="-16,-42", changeMap = "left" },
		{ map="-16,-43", changeMap = "left" },
		{ map="-16,-44", changeMap = "left" },
		{ map="-16,-45", changeMap = "left" },
		{ map="-29,-40", changeMap = "top" },
		{ map="-29,-41", changeMap = "top" },
		{ map="-29,-42", changeMap = "top" },
		{ map="-29,-44", changeMap = "top" },
		{ map="-29,-43", changeMap = "top" },
		{ map="-29,-46", changeMap = "top" },
		{ map="-29,-47", changeMap = "top" },
		{ map="-32,-47", changeMap = "right" },
		{ map = "147254", custom = comptage, door = "383" },
		{ map = "2885641", npcBank = true },
	}
end
