---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur : BiOcos
-- Type : Récolte
-- Zone : Pandala
-- Métier : Alchimiste
---------------------------------------------

DISPLAY_GATHER_COUNT = true -- Affiche le compteur de recoltes
MAX_PODS = 90 -- Retour en banque à 90% des PODS
ELEMENTS_TO_GATHER = {  } -- Elements à récolter ({} = tous)
OPEN_BAGS = true -- Ouverture automatique des sacs
BANK_GET_KAMAS = 0 -- Prend les Kamas en banque

function move()
	return {
		{ map="28,-41", gather = true, changeMap = "bottom" },
		{ map="28,-40", gather = true, changeMap = "bottom" },
		{ map="28,-39", gather = true, changeMap = "bottom" },
		{ map="28,-35", gather = true, changeMap = "bottom" },
		{ map="25,-42", gather = true, changeMap = "right" },
		{ map="26,-42", gather = true, changeMap = "right" },
		{ map="24,-42", gather = true, changeMap = "right" },
		{ map="23,-42", gather = true, changeMap = "right" },
		{ map="27,-41", changeMap = "right" },
		{ map="27,-42", gather = true, changeMap = "bottom" },
		{ map="28,-38", changeMap = "bottom" },
		{ map="28,-37", changeMap = "left" },
		{ map="27,-37", gather = true, changeMap = "bottom" },
		{ map="27,-36", changeMap = "bottom" },
		{ map="27,-35", changeMap = "right" },
		{ map="28,-34", changeMap = "bottom" },
		{ map="28,-33", gather = true, changeMap = "left" },
		{ map="27,-33", gather = true, changeMap = "left" },
		{ map="27,-31", gather = true, changeMap = "left" },
		{ map="21,-33", gather = true, changeMap = "left" },
		{ map="26,-33", gather = true, changeMap = "bottom" },
		{ map="26,-32", gather = true, changeMap = "right" },
		{ map="27,-32", gather = true, changeMap = "bottom" },
		{ map="26,-31", gather = true, changeMap = "left" },
		{ map="25,-30", gather = true, changeMap = "left" },
		{ map="24,-31", gather = true, changeMap = "left" },
		{ map="23,-30", gather = true, changeMap = "left" },
		{ map="22,-31", gather = true, changeMap = "left" },
		{ map="25,-31", changeMap = "bottom" },
		{ map="24,-30", gather = true, changeMap = "top" },
		{ map="23,-31", changeMap = "bottom" },
		{ map="22,-30", changeMap = "top" },
		{ map="21,-31", gather = true, changeMap = "top" },
		{ map="21,-32", gather = true, changeMap = "top" },
		{ map="20,-33", changeMap = "top" },
		{ map="20,-34", changeMap = "top" },
		{ map="20,-35", changeMap = "top" },
		{ map="20,-36", gather = true, changeMap = "top" },
		{ map="20,-37", changeMap = "top" },
		{ map="20,-38", gather = true, changeMap = "top" },
		{ map="20,-39", gather = true, changeMap = "right" },
		{ map="21,-40", gather = true, changeMap = "right" },
		{ map="22,-41", gather = true, changeMap = "right" },
		{ map="23,-41", changeMap = "top" },
		{ map="21,-39", gather = true, changeMap = "top" },
		{ map="22,-40", gather = true, changeMap = "top" },
		{ map = "12580", changeMap = "top" },
		{ map="24,-37", changeMap = "right" },
		{ map="25,-37", changeMap = "right" },
		{ map="26,-37", changeMap = "right" },
		{ map = "8129542", changeMap = "409" },
	}
end

function bank()
	return {
		{ map="28,-41", changeMap = "bottom" },
		{ map="28,-40", changeMap = "bottom" },
		{ map="28,-39", changeMap = "bottom" },
		{ map="28,-35", changeMap = "left" },
		{ map="25,-42", changeMap = "right" },
		{ map="26,-42", changeMap = "right" },
		{ map="24,-42", changeMap = "left" },
		{ map="23,-42", changeMap = "bottom" },
		{ map="27,-41", changeMap = "right" },
		{ map="27,-42", changeMap = "bottom" },
		{ map="28,-38", changeMap = "bottom" },
		{ map="28,-37", changeMap = "left" },
		{ map="27,-37", changeMap = "bottom" },
		{ map="27,-36", changeMap = "left" },
		{ map="27,-35", changeMap = "top" },
		{ map="28,-34", changeMap = "top" },
		{ map="28,-33", changeMap = "top" },
		{ map="27,-33", changeMap = "right" },
		{ map="27,-31", changeMap = "left" },
		{ map="21,-33", changeMap = "left" },
		{ map="26,-33", changeMap = "right" },
		{ map="26,-32", changeMap = "bottom" },
		{ map="27,-32", changeMap = "bottom" },
		{ map="26,-31", changeMap = "left" },
		{ map="25,-30", changeMap = "left" },
		{ map="24,-31", changeMap = "top" },
		{ map="23,-30", changeMap = "right" },
		{ map="22,-31", changeMap = "right" },
		{ map="25,-31", changeMap = "left" },
		{ map="24,-30", changeMap = "top" },
		{ map="23,-31", changeMap = "right" },
		{ map="22,-30", changeMap = "right" },
		{ map="21,-31", changeMap = "top" },
		{ map="21,-32", changeMap = "top" },
		{ map="20,-33", changeMap = "top" },
		{ map="20,-34", changeMap = "top" },
		{ map="20,-35", changeMap = "top" },
		{ map="20,-36", changeMap = "right" },
		{ map="20,-37", changeMap = "bottom" },
		{ map="20,-38", changeMap = "bottom" },
		{ map="20,-39", changeMap = "bottom" },
		{ map="21,-40", changeMap = "bottom" },
		{ map="22,-41", changeMap = "bottom" },
		{ map="23,-41", changeMap = "left" },
		{ map="21,-39", changeMap = "left" },
		{ map="22,-40", changeMap = "left" },
		{ map="21,-36", changeMap = "right" },
		{ map="22,-36", changeMap = "right" },
		{ map="23,-36", changeMap = "right" },
		{ map="24,-32", changeMap = "top" },
		{ map="24,-33", changeMap = "top" },
		{ map="24,-34", changeMap = "top" },
		{ map="24,-35", changeMap = "top" },
		{ map="26,-36", changeMap = "left" },
		{ map="25,-36", changeMap = "left" },
		{ map = "12580", door = "284" },
		{ map = "8129542", npcBank = true },
	}
end
