---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur : Vallenstriker
-- Type : Combats
-- Zone : Forét d'Amakna
---------------------------------------------

MAX_PODS = 90
OPEN_BAGS = true

AUTO_DELETE = {  }

MIN_MONSTERS = 4
MAX_MONSTERS = 8
FORBIDDEN_MONSTERS = {  }
MANDATORY_MONSTERS = {  }
DISPLAY_FIGHT_COUNT = true
DISPLAY_BANK_COUNT = true

function move()
	return {
		{ map="11,12", fight = true, changeMap = "left" },
		{ map="10,12", fight = true, changeMap = "right|left" },
		{ map="9,12", fight = true, changeMap = "right|left" },
		{ map="8,12", fight = true, changeMap = "right|left" },
		{ map="7,12", fight = true, changeMap = "right|left" },
		{ map="6,12", fight = true, changeMap = "right|left" },
		{ map="5,12", fight = true, changeMap = "right|left" },
		{ map="4,12", fight = true, changeMap = "bottom|right" },
		{ map="5,13", fight = true, changeMap = "right|left|bottom|top" },
		{ map="6,13", fight = true, changeMap = "right|left|bottom|top" },
		{ map="7,13", fight = true, changeMap = "left|bottom|top|right" },
		{ map="5,14", fight = true, changeMap = "right|left|bottom|top" },
		{ map="6,14", fight = true, changeMap = "right|left|bottom|top" },
		{ map="7,14", fight = true, changeMap = "left|bottom|top" },
		{ map="7,15", fight = true, changeMap = "left|bottom|top" },
		{ map="6,15", fight = true, changeMap = "right|left|bottom|top" },
		{ map="8,13", fight = true, changeMap = "left|top" },
		{ map="7,16", fight = true, changeMap = "top|bottom" },
		{ map="6,16", fight = true, changeMap = "top|bottom|right|left" },
		{ map="6,17", fight = true, changeMap = "top|bottom|right|left" },
		{ map="7,17", fight = true, changeMap = "top|bottom|left" },
		{ map="7,18", fight = true, changeMap = "top|bottom|left" },
		{ map="7,19", fight = true, changeMap = "top|left|right" },
		{ map="8,19", fight = true, changeMap = "top|left|right" },
		{ map="9,19", fight = true, changeMap = "top|left" },
		{ map="9,18", fight = true, changeMap = "bottom" },
		{ map="6,19", fight = true, changeMap = "left|right|top" },
		{ map="5,19", fight = true, changeMap = "left|right|top" },
		{ map="4,19", fight = true, changeMap = "right|top" },
		{ map="5,18", fight = true, changeMap = "right|top|left|bottom" },
		{ map="6,18", fight = true, changeMap = "right|top|left|bottom" },
		{ map="5,17", fight = true, changeMap = "right|top|left|bottom" },
		{ map="5,16", fight = true, changeMap = "right|top|left|bottom" },
		{ map="5,15", fight = true, changeMap = "right|top|left|bottom" },
		{ map="4,13", fight = true, changeMap = "right|top|bottom" },
		{ map="4,14", fight = true, changeMap = "right|top|bottom" },
		{ map="4,15", fight = true, changeMap = "right|top|bottom" },
		{ map="4,16", fight = true, changeMap = "right|top|bottom" },
		{ map="4,17", fight = true, changeMap = "right|top|bottom" },
		{ map="4,18", fight = true, changeMap = "right|top|bottom" },
		{ map="-1,13", changeMap = "right" },
		{ map="0,13", changeMap = "right" },
		{ map="1,13", changeMap = "right" },
		{ map="2,13", changeMap = "right" },
		{ map="3,13", changeMap = "right" },
		{ map="5,7", changeMap = "bottom" },
		{ map="5,8", changeMap = "bottom" },
		{ map="5,9", changeMap = "bottom" },
		{ map="5,10", changeMap = "bottom" },
		{ map="5,11", changeMap = "bottom" },
		{ map="0,24", changeMap = "right" },
		{ map="-1,24", changeMap = "right" },
		{ map="2,24", changeMap = "right" },
		{ map="4,24", changeMap = "top" },
		{ map="3,24", changeMap = "right" },
		{ map="4,23", changeMap = "top" },
		{ map="4,22", changeMap = "top" },
		{ map="4,21", changeMap = "top" },
		{ map="4,20", changeMap = "top" },
		{ map="10,22", changeMap = "top" },
		{ map="10,21", changeMap = "top" },
		{ map="10,20", changeMap = "top" },
		{ map="10,19", changeMap = "left" },
		{ map="9,20", changeMap = "top" },
		{ map="8,20", changeMap = "top" },
		{ map="7,20", changeMap = "top" },
		{ map="6,20", changeMap = "top" },
		{ map="5,20", changeMap = "top" },
		{ map="3,19", changeMap = "right" },
		{ map="3,18", changeMap = "right" },
		{ map="3,17", changeMap = "right" },
		{ map="3,16", changeMap = "right" },
		{ map="3,15", changeMap = "right" },
		{ map="3,14", changeMap = "right" },
		{ map="3,12", changeMap = "right" },
		{ map="4,11", changeMap = "bottom" },
		{ map="6,11", changeMap = "bottom" },
		{ map="7,11", changeMap = "bottom" },
		{ map="8,11", changeMap = "bottom" },
		{ map="9,11", changeMap = "bottom" },
		{ map="10,11", changeMap = "bottom" },
		{ map="11,11", changeMap = "bottom" },
		{ map="12,12", changeMap = "left" },
		{ map="1,24", changeMap = "right" },
		{ map="4,10", changeMap = "bottom" },
		{ map="4,9", changeMap = "bottom" },
		{ map="4,8", changeMap = "bottom" },
		{ map="4,7", changeMap = "bottom" },
		{ map="4,6", changeMap = "bottom" },
		{ map="4,5", changeMap = "bottom" },
		{ map="4,4", changeMap = "bottom" },
		{ map="4,3", changeMap = "bottom" },
		{ map="4,2", changeMap = "bottom" },
		{ map="4,1", changeMap = "bottom" },
		{ map="2,0", changeMap = "bottom" },
		{ map="2,-1", changeMap = "bottom" },
		{ map = "0", changeMap = "bottom" },
		{ map="2,1", changeMap = "right" },
		{ map="3,1", changeMap = "right" },
		{ map="11,13", changeMap = "top" },
		{ map="8,14", changeMap = "top|left" },
		{ map="8,15", changeMap = "left" },
		{ map="8,18", changeMap = "bottom" },
		{ map = "0", changeMap = "410" },
	}
end

function bank()
	return {
		{ map="11,12", changeMap = "left" },
		{ map="10,12", changeMap = "left" },
		{ map="9,12", changeMap = "left" },
		{ map="8,12", changeMap = "left" },
		{ map="7,12", changeMap = "left" },
		{ map="6,12", changeMap = "left" },
		{ map="5,12", changeMap = "left" },
		{ map="4,12", changeMap = "top" },
		{ map="5,13", changeMap = "left" },
		{ map="6,13", changeMap = "left" },
		{ map="7,13", changeMap = "left" },
		{ map="5,14", changeMap = "left" },
		{ map="6,14", changeMap = "left" },
		{ map="7,14", changeMap = "left" },
		{ map="7,15", changeMap = "left" },
		{ map="6,15", changeMap = "left" },
		{ map="8,13", changeMap = "left" },
		{ map="7,16", changeMap = "left" },
		{ map="6,16", changeMap = "left" },
		{ map="6,17", changeMap = "left" },
		{ map="7,17", changeMap = "left" },
		{ map="7,18", changeMap = "left" },
		{ map="7,19", changeMap = "left" },
		{ map="8,19", changeMap = "left" },
		{ map="9,19", changeMap = "left" },
		{ map="9,18", changeMap = "bottom" },
		{ map="6,19", changeMap = "left" },
		{ map="5,19", changeMap = "left" },
		{ map="4,19", changeMap = "top" },
		{ map="5,18", changeMap = "left" },
		{ map="6,18", changeMap = "left" },
		{ map="5,17", changeMap = "left" },
		{ map="5,16", changeMap = "left" },
		{ map="5,15", changeMap = "left" },
		{ map="4,13", changeMap = "top" },
		{ map="4,14", changeMap = "top" },
		{ map="4,15", changeMap = "top" },
		{ map="4,16", changeMap = "top" },
		{ map="4,17", changeMap = "top" },
		{ map="4,18", changeMap = "top" },
		{ map="4,11", changeMap = "top" },
		{ map="4,10", changeMap = "top" },
		{ map="4,9", changeMap = "top" },
		{ map="4,8", changeMap = "top" },
		{ map="4,7", changeMap = "top" },
		{ map="4,6", changeMap = "top" },
		{ map="4,5", changeMap = "top" },
		{ map="4,4", changeMap = "top" },
		{ map="4,3", changeMap = "top" },
		{ map="4,2", changeMap = "top" },
		{ map="4,1", changeMap = "top" },
		{ map="4,0", changeMap = "left" },
		{ map="3,0", changeMap = "left" },
		{ map="2,0", changeMap = "top" },
		{ map="2,-1", changeMap = "top" },
		{ map = "88081177", door = "216" },
		{ map = "99095051", npcBank = true },
	}
end


function phenix()
	return {
		{ map="8,16", changeMap = "right" },
		{ map="9,16", changeMap = "right" },
		{ map="11,16", changeMap = "right" },
		{ map="10,16", changeMap = "right" },
		{ map="12,16", changeMap = "right" },
		{ map="13,16", changeMap = "right" },
		{ map="14,16", changeMap = "top" },
		{ map="14,15", changeMap = "top" },
		{ map="14,14", changeMap = "left" },
		{ map="13,14", changeMap = "top" },
		{ map="13,13", changeMap = "top" },
		{ map="13,12", changeMap = "left" },
		{ map="12,11", changeMap = "bottom" },
		{ map="11,12", changeMap = "right" },
		{ map="11,11", changeMap = "right|bottom" },
		{ map="9,15", changeMap = "bottom" },
		{ map="9,14", changeMap = "bottom" },
		{ map="10,14", changeMap = "bottom" },
		{ map="10,15", changeMap = "bottom" },
		{ map="11,15", changeMap = "bottom" },
		{ map="8,17", changeMap = "top" },
		{ map="9,17", changeMap = "top" },
		{ map="10,17", changeMap = "top" },
		{ map="11,17", changeMap = "top" },
		{ map="12,17", changeMap = "top" },
		{ map="12,12", phenix = "184" },
	}
end

