---------------------------------------------
-- Script created with aScripter v2
---------------------------------------------
-- Créateur : BiOcos mais EDIT par alex621457
-- Type : Récolte
-- Zone : Dents de pierre
-- Métier : Paysan
---------------------------------------------

DISPLAY_GATHER_COUNT = true -- Affiche le compteur de recoltes
MAX_PODS = 90 -- Retour en banque à 90% des PODS
ELEMENTS_TO_GATHER = {256, 261 } -- Elements à récolter ({} = tous)
OPEN_BAGS = true -- Ouverture automatique des sacs
BANK_GET_KAMAS = 0 -- Prend les Kamas en banque

function move()
	return {

		{ map="-6,-51", changeMap = "top" },
		{ map="-32,-56", changeMap = "right" },
		{ map="-31,-56", changeMap = "right" },
		{ map="-30,-56", changeMap = "right" },
		{ map="-29,-56", changeMap = "right" },
		{ map="-28,-56", changeMap = "right" },
		{ map="-27,-56", changeMap = "right" },
		{ map="-26,-56", changeMap = "right" },
		{ map="-25,-56", changeMap = "bottom" },
		{ map="-25,-55", changeMap = "bottom" },
		{ map="-25,-54", changeMap = "bottom" },
		{ map="-25,-53", changeMap = "bottom" },
		{ map="-25,-52", changeMap = "bottom" },
		{ map="-25,-51", changeMap = "bottom" },
		{ map="-25,-50", changeMap = "bottom" },
		{ map="-25,-49", changeMap = "bottom" },
		{ map="-25,-48", changeMap = "bottom" },
		{ map="-25,-47", changeMap = "right" },
		{ map="-24,-47", changeMap = "bottom" },
		{ map="-24,-46", changeMap = "right" },
		{ map="-23,-46", changeMap = "top" },
		{ map="-23,-47", changeMap = "right" },
		{ map="-22,-47", changeMap = "right" },
		{ map="-21,-47", changeMap = "right" },
		{ map="-20,-47", changeMap = "right" },
		{ map="-19,-47", changeMap = "right" },
		{ map="-18,-47", changeMap = "right" },
		{ map="-17,-47", changeMap = "right" },
		{ map="-16,-47", changeMap = "bottom" },
		{ map="-16,-46", changeMap = "bottom" },
		{ map="-16,-45", changeMap = "bottom" },
		{ map="-16,-44", changeMap = "right" },
		{ map="-15,-44", changeMap = "right" },
		{ map="-14,-44", changeMap = "right" },
		{ map="-13,-44", changeMap = "right" },
		{ map="-12,-44", changeMap = "top" },
		{ map="-12,-45", changeMap = "top" },
		{ map="-12,-46", changeMap = "right" },
		{ map="-11,-46", changeMap = "top" },
		{ map="-11,-47", changeMap = "top" },
		{ map="-11,-48", changeMap = "top" },
		{ map="-11,-49", changeMap = "top" },
		{ map="-11,-50", changeMap = "right" },
		{ map="-10,-50", changeMap = "right" },
		{ map="-9,-50", changeMap = "top" },
		{ map="-9,-51", changeMap = "right" },
		{ map="-8,-51", changeMap = "right" },
		{ map="-7,-51", changeMap = "right" },
		{ map = "147254", changeMap = "top" },
		{ map="-31,-55", changeMap = "top" },
		{ map="-6,-54", gather = true, changeMap = "left" },
		{ map="-7,-54", changeMap = "top" },
		{ map="-7,-55", gather = true, changeMap = "right" },
		{ map="-6,-55", gather = true, changeMap = "top" },
		{ map="-5,-56", gather = true, changeMap = "top" },
		{ map="-4,-56", gather = true, changeMap = "bottom" },
		{ map="-4,-55", gather = true, changeMap = "bottom" },
		{ map="-4,-54", gather = true, changeMap = "right" },
		{ map="-5,-59", gather = true, changeMap = "right" },
		{ map="-4,-59", gather = true, changeMap = "bottom" },
		{ map="-4,-58", gather = true, changeMap = "right" },
		{ map="-4,-57", gather = true, changeMap = "bottom" },
		{ map="-3,-58", gather = true, changeMap = "bottom" },
		{ map="-3,-57", gather = true, changeMap = "left" },
		{ map="-6,-52", gather = true, changeMap = "top" },
		{ map="-6,-53", gather = true, changeMap = "top" },
		{ map="-6,-56", gather = true, changeMap = "right" },
		{ map="-6,-57", gather = true, changeMap = "top" },
		{ map="-6,-58", gather = true, changeMap = "right" },
		{ map="-5,-58", gather = true, changeMap = "top" },
		{ map="-5,-57", gather = true, changeMap = "left" },
		{ map="-2,-51", gather = true, changeMap = "left" },
		{ map="-3,-51", gather = true, changeMap = "left" },
		{ map="-3,-54", changeMap = "bottom" },
		{ map="-3,-53", changeMap = "right" },
		{ map="-2,-53", changeMap = "bottom" },
		{ map="-2,-52", changeMap = "right" },
		{ map="-1,-52", changeMap = "bottom" },
		{ map="-1,-51", changeMap = "left" },
		{ map="-4,-51", changeMap = "left" },
		{ map="-5,-51", changeMap = "left" },
		{ map = "2885641", changeMap = "424" },
	}
end

function bank()
	return {
		{ map="-6,-52", changeMap = "bottom" },
		{ map="-6,-53", changeMap = "bottom" },
		{ map="-6,-56", changeMap = "bottom" },
		{ map="-6,-57", changeMap = "bottom" },
		{ map="-6,-58", changeMap = "bottom" },
		{ map="-5,-58", changeMap = "bottom" },
		{ map="-5,-57", changeMap = "bottom" },
		{ map="-6,-51", changeMap = "left" },
		{ map="-31,-56", changeMap = "bottom" },
		{ map="-30,-56", changeMap = "left" },
		{ map="-29,-56", changeMap = "left" },
		{ map="-28,-56", changeMap = "left" },
		{ map="-27,-56", changeMap = "left" },
		{ map="-26,-56", changeMap = "left" },
		{ map="-25,-56", changeMap = "left" },
		{ map="-25,-55", changeMap = "top" },
		{ map="-25,-54", changeMap = "top" },
		{ map="-25,-53", changeMap = "top" },
		{ map="-25,-52", changeMap = "top" },
		{ map="-25,-51", changeMap = "top" },
		{ map="-25,-50", changeMap = "top" },
		{ map="-25,-49", changeMap = "top" },
		{ map="-25,-48", changeMap = "top" },
		{ map="-25,-47", changeMap = "top" },
		{ map="-24,-47", changeMap = "left" },
		{ map="-24,-46", changeMap = "top" },
		{ map="-23,-46", changeMap = "left" },
		{ map="-23,-47", changeMap = "bottom" },
		{ map="-23,-46", changeMap = "left" },
		{ map="-21,-47", changeMap = "left" },
		{ map="-21,-46", changeMap = "top" },
		{ map="-20,-46", changeMap = "left" },
		{ map="-20,-47", changeMap = "bottom" },
		{ map="-19,-47", changeMap = "left" },
		{ map="-18,-47", changeMap = "left" },
		{ map="-17,-47", changeMap = "left" },
		{ map="-16,-47", changeMap = "left" },
		{ map="-16,-46", changeMap = "top" },
		{ map="-16,-45", changeMap = "top" },
		{ map="-16,-44", changeMap = "top" },
		{ map="-15,-44", changeMap = "left" },
		{ map="-14,-44", changeMap = "left" },
		{ map="-13,-44", changeMap = "left" },
		{ map="-12,-44", changeMap = "left" },
		{ map="-12,-45", changeMap = "bottom" },
		{ map="-11,-45", changeMap = "left" },
		{ map="-11,-46", changeMap = "bottom" },
		{ map="-11,-47", changeMap = "bottom" },
		{ map="-11,-48", changeMap = "bottom" },
		{ map="-11,-49", changeMap = "bottom" },
		{ map="-11,-50", changeMap = "bottom" },
		{ map="-10,-50", changeMap = "left" },
		{ map="-9,-50", changeMap = "left" },
		{ map="-9,-51", changeMap = "bottom" },
		{ map="-8,-51", changeMap = "left" },
		{ map="-7,-51", changeMap = "left" },
		{ map="-31,-55", changeMap = "bottom" },
		{ map="-6,-54", changeMap = "bottom" },
		{ map="-7,-54", changeMap = "right" },
		{ map="-7,-55", changeMap = "right" },
		{ map="-6,-55", changeMap = "bottom" },
		{ map="-5,-56", changeMap = "left" },
		{ map="-4,-56", changeMap = "bottom" },
		{ map="-4,-55", changeMap = "bottom" },
		{ map="-4,-54", changeMap = "right" },
		{ map="-5,-59", changeMap = "bottom" },
		{ map="-4,-59", changeMap = "bottom" },
		{ map="-4,-58", changeMap = "right" },
		{ map="-4,-57", changeMap = "bottom" },
		{ map="-3,-58", changeMap = "bottom" },
		{ map="-3,-57", changeMap = "left" },
		{ map="-3,-54", changeMap = "bottom" },
		{ map="-3,-53", changeMap = "right" },
		{ map="-2,-53", changeMap = "bottom" },
		{ map="-2,-52", changeMap = "right" },
		{ map="-1,-52", changeMap = "bottom" },
		{ map="-1,-51", changeMap = "left" },
		{ map="-2,-51", changeMap = "left" },
		{ map="-3,-51", changeMap = "left" },
		{ map="-4,-51", changeMap = "left" },
		{ map="-5,-51", changeMap = "left" },
		{ map = "147254", door = "383" },
		{ map = "2885641", npcBank = true },
	}
end
